### ISSUE TITLE
Change "To be added." text in deprecated items to something else.

### ISSUE THREAD

**Issue by MichaelNorman** [mono/api-doc-tools#1]
It would make counting unfinished work easier if "To be added." was exclusively reserved for work items that are actually candidates for further work. Deprecated and unavailable items do not satisfy this implied predicate, so it would be nice if classes, structs, enums, and their fields, properties, and methods that are deprecated did not have the "To be added." placeholder text.

mdoc/monodoc should change the boilerplate text for these when it discovers that these items are deprecated.

**Comment by joelmartinez** [comment]
Closing, as this is now an issue best handled external to mdoc ... particularly for Microsoft teams, who's content is hosted and displayed by OPS.

**Comment by lobrien** [comment]
![200](https://user-images.githubusercontent.com/181571/62402179-4143f900-b522-11e9-9f97-4d54149fed81.gif)
