### ISSUE TITLE
[mdoc] Analytics mode

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#100]
When `mdoc` runs, it would be helpful to get some statistics on what was actually produced. Example metrics would include:

* Total types generated from a framework
* Total namespaces generated from a framework

If that information is produced to a CSV with the help of a flag, that would solve the ask.

**Comment by joelmartinez** [comment]
@dend do you want this to be the entire sum of types and namespaces ... or do you want it to be differential, which is to say, how many were added/removed since the last run ?

**Comment by dend** [comment]
@joelmartinez I think it would be interesting to get both. Something along the lines of:

```
framework-1.0
------------
Types: X
Types Added: 0
Types Removed: 0

Namespaces: Y
Namespaces Added: 0
Namespaces Removed: 0

Members: Z
Members Added: 0
Members Removed: 0

framework-2.0
------------
Types: X
Types Added: 0
Types Removed: 0

Namespaces: Y
Namespaces Added: 0
Namespaces Removed: 0

Members: Z
Members Added: 0
Members Removed: 0
```
