### ISSUE TITLE
[mdoc] Frameworks Mode - <AssemblyInfo> should show which framework is it in

### ISSUE THREAD

**Issue by TianqiZhang** [mono/api-doc-tools#103]
For .Net, there are many cases that a type is in different assemblies per different framework. For example, Dictionary<TKey,TValue> is in System.Collections.dll for .Net Core 2.0, but is in mscorlib.dll for .Net Frameworks 4.7.

Right now the list of <AssemblyInfo> in ECMAXML does not tell us which assembly belongs to which framework. We really need this information though, otherwise we can't generate correct intellisense file for VisualStudio.

**Comment by dend** [comment]
@joelmartinez looks like another use case for `FrameworkAlternate`

**Comment by joelmartinez** [comment]
I see ... so to use a concrete example, [this xml segment](https://github.com/dotnet/docs/blob/master/xml/System.Collections.Generic/Dictionary%602.xml#L5-L19) is what is in question. There's a few different approaches we could take:

## Approach 1: framework per `AssemblyInfo`
Just list every framework/version in the corresponding assemblyinfo

```xml
  <AssemblyInfo>
    <AssemblyName>System.Collections</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <AssemblyVersion>4.0.10.0</AssemblyVersion>
    <AssemblyVersion>4.1.0.0</AssemblyVersion>
    <Framework>netcore-1.0</Framework>
    <Framework>netcore-1.1</Framework>
    <Framework>netcore-2.0</Framework>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <Framework>xamarinandroid-7.1</Framework>
    <Framework>xamarinios-10.8</Framework>
    <Framework>xamarinmac-3.0</Framework>
    <Framework>netframework-4.5.1</Framework>
    <Framework>netframework-4.5.2</Framework>
    <Framework>netframework-4.6.1</Framework>
    <Framework>netframework-4.6.2</Framework>
    <Framework>netframework-4.6</Framework>
    <Framework>netframework-4.7</Framework>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <Framework>netstandard-1.0</Framework>
    <Framework>netstandard-1.1</Framework>
    <Framework>netstandard-1.2</Framework>
    <Framework>netstandard-1.3</Framework>
    <Framework>netstandard-1.4</Framework>
    <Framework>netstandard-1.5</Framework>
    <Framework>netstandard-1.6</Framework>
    <Framework>netstandard-2.0</Framework>
  </AssemblyInfo>
```

## Approach 2: framework _Moniker_ per `AssemblyInfo`
As you can see in the example above, the number of `<Framework>` elements will just grow over time as more and more versions are tracked. However, depending on the outcome of [this other work](https://github.com/mono/api-doc-tools/issues/85#issuecomment-317737472) we might be able to easily separate out that version information ... so if the version of the target platform isn't necessary for this, then the following might work:

```xml
  <AssemblyInfo>
    <AssemblyName>System.Collections</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <AssemblyVersion>4.0.10.0</AssemblyVersion>
    <AssemblyVersion>4.1.0.0</AssemblyVersion>
    <Framework>netcore</Framework>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <Framework>netframework</Framework>
    <Framework>xamarinandroid</Framework>
    <Framework>xamarinios</Framework>
    <Framework>xamarinmac</Framework>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <Framework>netstandard</Framework>
  </AssemblyInfo>
```
Unfortunately, this assumes that a type will never move from one assembly to another in the same framework (ie. it will always be a part of `mscorlib` on `netstandard`). 

Would love to hear your thoughts on which direction you'd like to go ... or if you have another idea altogether about how to track this data :)

**Comment by TianqiZhang** [comment]
@joelmartinez thanks for your response. I think the assumption with Approach 2 is a little too risky. How about provide this info in FrameworkIndex files?  Which means, we change FrameworkIndex file schema to something like this:
```xml
<Framework Name="netstandard-1.5">
  <Assembly Name="System.dll" Version="4.0.0.0">
    <Namespace Name="System">
      <Type Name="System.Action" Id="T:System.Action" />
      <Type Name="System.Action`1" Id="T:System.Action`1" />
      <Type Name="System.Action`10" Id="T:System.Action`10" />
```

**Comment by joelmartinez** [comment]
@TianqiZhang unfortunately that would explode the size of the framework index files ... because then you'd have to duplicate all the namespaces and types for every version of an assembly, and these files are already quite large (github won't display them in their editor)

**Comment by TianqiZhang** [comment]
@joelmartinez for a specific framework, every dll will only have one version, right? so the framework index file's size would merely change, we are just adding an extra <Assembly> layer in it.

**Comment by dend** [comment]
@TianqiZhang the problem with that will be that now we have an extra layer of grouping per-assembly. Many frameworks have several assemblies, so we will end up with somewhat duplicative grouping. It seems that option (1) would be the sane one in this case.

**Comment by TianqiZhang** [comment]
@dend it is very unlikely that a namespace would appear in multiple assemblies in the same framework, right? So every `<Assembly>` group will contain different namespaces, there won't be much dup.

**Comment by TianqiZhang** [comment]
@joelmartinez @dend any thoughts? If you guys still have concerns about putting it in framework index file , how about we go with Approach 1 but only do it on type level? We can safely assume that members should have the same mapping with their parent type, so there's no need to add such info on member level.

**Comment by joelmartinez** [comment]
Re-reviewing this issue after some time to reflect ... Is there a reason why don't we simply include the assembly info in a group at the top of each frameworks index file? 

So it would look as such:

```xml
<Framework Name="netstandard-1.5">
  <Assemblies>
    <Assembly Name="System.Collections" Version="4.0.0.0" />
    <Assembly Name="mscorlib" Version="2.0.5.0" />
    ...
  </Assemblies>
  ...
```

- The frameworks index file tells you which type and member is included in a framework.
- Every type and member also tells you what assembly/version it appears in.

This should give you the information to produce the intellisense file for a framework ... thoughts?

**Comment by TianqiZhang** [comment]
@joelmartinez this looks great, when can we see this implemented? 😆

**Comment by joelmartinez** [comment]
@den @TianqiZhang so in light of #342 ... do we want the list of assemblies in the framework index file to be the explicit list that was included in the moniker? Or do we want to include all of the "forwarded to" assemblies?

To be explicit about the scenario, let's say we have a set of assemblies (`a.dll`, `b.dll`) in moniker `fx`; and `b.dll` has types forwarded to `fwded.dll`.

**Do we want:** 

- `fx.dll` to include **only** `a.dll` and `b.dll`?

*or*

- `fx.dll` to include `a.dll`, `b.dll` **and** `fwded.dll`

?

**Comment by TianqiZhang** [comment]
@joelmartinez the intellisense build will only need "real" assemblies, and I think in the future if we show different assemblies for different monikers on api web page, users wouldn't care about forwarded types. I quote from @mairaw: "Ideally, this assembly info for forwarded types should only show up in the metadata and not in the UI. ".

So I don't mind if we include `fwded.dll` in the list, as long as we can easily filter them.

**Comment by TianqiZhang** [comment]
@joelmartinez just to confirm, right now in framework index file under `<Framework>/<Assemblies>`, all assemblies are "real" assemblies, no "forwarded" assemlbies, right? I plan to consume this list and use it to replace my old "moniker2assembly" mapping :D

**Comment by joelmartinez** [comment]
@TianqiZhang yes that is correct … this list should only contain the exact list of assemblies that were in the moniker folder (for example, in the `binaries/dotnet/*` repo). It shouldn't contain any of the assemblies in any of the dependencies folders, or in any of the system framework folders.

**Comment by TianqiZhang** [comment]
@joelmartinez I mean, did mdoc filter out the forwarded assemblies? For example, I'm still seeing mscorlib in netcore-2.1.xml:
```xml
<Framework Name="netcore-2.1">
  <Assemblies>
    <Assembly Name="Microsoft.CSharp" Version="4.0.0.0" />
    <Assembly Name="Microsoft.VisualBasic" Version="10.0.0.0" />
    <Assembly Name="Microsoft.Win32.Primitives" Version="4.1.1.0" />
    <Assembly Name="mscorlib" Version="4.0.0.0" />
```
However mscorlib.dll is only a forwarded dll in .NET Core.
Can we add another attribute to indicate if an assembly is forwarded? For example:
`<Assembly Name="mscorlib" Version="4.0.0.0" Forwarded="true"/>`

**Comment by joelmartinez** [comment]
@TianqiZhang I agree that we need to track whether it's forwarded or not … however in this case, `mscorlib` is literally included in the list of binaries to be reflected:  
https://apidrop.visualstudio.com/_git/binaries?path=%2Fdotnet%2Fnetcore-2.1%2Fmscorlib.dll&version=GBmaster

In this case, it will always be included because the _intent_ of including the assembly in that folder is telling mdoc that you want it specifically documented. If perhaps it was added in order to properly resolve a dependency (instead of using whatever system mscorlib is installed), then it should probably moved to the [corresponding `dependencies` folder](https://apidrop.visualstudio.com/_git/binaries?path=%2Fdotnet%2Fdependencies%2Fnetcore-2.1&version=GBmaster)
