### ISSUE TITLE
EII events should not be treated as private

### ISSUE THREAD

**Issue by TianqiZhang** [mono/api-doc-tools#106]
We recently found that mdoc is ignoring Explicit Interface Implementation events, like they were private members. Take [System.Web.UI.WebControls.ListView](https://docs.microsoft.com/en-us/dotnet/api/System.Web.UI.WebControls.ListView?view=netframework-4.7#explicit_interface_implementations_) as an example, according to the [source code](https://referencesource.microsoft.com/#System.Web.Extensions/UI/WebControls/ListView.cs), it has an EII event called `IPageableItemContainer.TotalRowCountAvailable`:
```csharp
[SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes",
                 Justification = "Unlikely that a derived type would re-implement this event.")]
event EventHandler<PageEventArgs> IPageableItemContainer.TotalRowCountAvailable {
    add {
        Events.AddHandler(EventTotalRowCountAvailable, value);
    }
    remove {
        Events.RemoveHandler(EventTotalRowCountAvailable, value);
    }
}
```

However this member is not in the xml generated by mdoc: [ListView.zip](https://github.com/mono/api-doc-tools/files/1207460/ListView.zip). I doubled checked with ildasm, the dll does contain this member.

**Comment by dend** [comment]
Per internal thread, this is an issue that is causing API losses, therefore a blocking migration bug. We will need to prioritize this high.

**Comment by joelmartinez** [comment]
@TianqiZhang and @dend ... I just wanted to double check that this was still an issue, since I changed the way that mdoc handles EII in release [v5.0.0.24](https://github.com/mono/api-doc-tools/releases/tag/preview-5.0.0.24) on sept 21st. Can we double check?

**Comment by dend** [comment]
I don't see the EII reference in the XML file even with the content generated from the latest version of `mdoc`. @TianqiZhang @mairaw - can you please confirm my assessment?

**Comment by TianqiZhang** [comment]
@joelmartinez @dend I confirm that this is still a issue, we cannot see the expected member described in this issue.
