### ISSUE TITLE
[mdoc] Support for pulling all DLLs from a folder natively

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#11]
Currently, `mdoc` on Windows does not support pulling DLLs from the entire folder (given that PS and BATCH do not support `*.dll`). 

Would be good to have a custom parameter (e.g. `--scanfolder FOLDER_PATH`) that will enable pulling all DLLs from folder and its subfolders.

**Comment by jonpryor** [comment]
This is becoming somewhat duplicative of Issue #13, in that the specification of "frameworks"/"platforms" would also be dealt with as directory structures, requiring the ability to scan folders.

Consequently, is *this* PR -- PR #11 -- required? Is there need to recurse assemblies within a directory tree *without* associated framework information?

**Comment by joelmartinez** [comment]
@jonpryor I think it could still be a nice feature ... in addition to other things like supporting `~`, which works well on *nix since the shell expands that path before it hits the program, but fails on windows.

Also, the PR didn't link correctly ... which PR were you referring to?

**Comment by jonpryor** [comment]
The feature could still be useful, in which case I nominate `mdoc update -recurse PATH` as the syntax. See also the mcs.exe `-recurse` option.

> in addition to other things like supporting `~`,

I don't understand what you mean by this. `~` is `$HOME`; while handy, that's probably only useful on "your" machine, not for use in e.g. a git repo which may be shared amongst *multiple* people placing their git checkout into *different* directories. As such, "supporting `~`" seems as useful as "supporting `%HOME%`, i.e. not *really* all that useful.

> which PR were you referring to?

[PR #13, "Support different platform variants and versions."](https://github.com/mono/api-doc-tools/issues/13)
