### ISSUE TITLE
[mdoc] EII & private interfaces

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#110]
We have an API:
https://github.com/Microsoft/xbox-live-api/blob/master/Source/Services/Achievements/WinRT/AchievementService_WinRT.h

When this is built into a WinMD (@joelmartinez already has the binaries covered), we end up with no methods being shown in the ECMAXML for AchievementService.

According to original investigation:

> the interface in question is an explicitly implemented interface from a private interface `__IAchievementServicePublicNonVirtuals` So the issue is that, with that interface being private, it wouldn’t be documented, thus `mdoc ` does not document those explicitly implemented members since you can’t use them

**Comment by joelmartinez** [comment]
[this](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/monodocer.cs#L1335-L1351) is the relevant code that is causing these members to be excluded from documentation. This is probably also related to #106, and tangentially to #92

**Comment by joelmartinez** [comment]
Ok ... so we do actually have a unit test that _seemingly_ addresses this exact scenario, and it suggests that the current behavior is correct. 

1. This test class has [a method](https://github.com/mono/api-doc-tools/blob/master/mdoc/Test/DocTest-InternalInterface.cs#L12).
2. That method is part of an [internal interface](https://github.com/mono/api-doc-tools/blob/master/mdoc/Test/DocTest-InternalInterface.cs#L6).
3. `BarMeth` is implemented publicly ... while other methods of `MyInternalInterface` are implemented explicitly.
4. The resulting EcmaXML contains [`BarMeth`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Test/en.expected-internal-interface/MyNamespace/MyClass.xml#L51), while excluding the other explicitly implemented members.

So, this leads me to believe that the assemblies in question are doing _something else_ in the metadata ... something unexpected. Unfortunately, I'm not as familiar with c++/cli (or whatever mechanism they're using to create the winmd language projections) to know what might be happening behind the scenes. 

thoughts on how we might proceed, @dend?
