### ISSUE TITLE
[mdoc] Lookup for dependencies in subfolders

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#112]
We are currently running into the issue where we have multiple dependencies with different versions but the same names (especially necessary in Frameworks mode). Currently, the dependency resolver only looks in the root folder for any dependencies - we need to modify that behavior to make sure that we search subfolders.

Given that we are working with versioned content, we might need to take a three-step approach:

1. Search for a library in folder/subfolders with the exact searched name and version.
2. If not found, search folder/subfolders for the library with the exact name and bigger (rev-d) version.
3. If not found, search folder/subfolders for the library with the exact name.

**Comment by joelmartinez** [comment]
I'm going to add a flag for anyone that might want to _disable_ this functionality and go back to the old functionality. `-disable-searchdir-recurse`
