### ISSUE TITLE
[mdoc] Insert default thread safety information through a custom attribute

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#113]
Currently, the `<threadsafety>` element is used to describe whether certain types are thread-safe. However, its content has to be manually entered.

The proposal is to have a custom attribute within the element, that will allow tooling that reads ECMAXML to automatically insert boilerplate text, such as `<threadsafe supported="true">`

**Comment by dend** [comment]
Per @TianqiZhang, there is an additional ask:

* "All public *static* members of this class are thread safe.”
  * Can map to: `<threadsafe supported=”true” memberScope=”static”/>`
* “All members of this class are thread safe”
  * Can map to: `<threadsafe supported=”true” memberScope=”all” />` or just `<threadsafe supported=”true” />`
* “this class is not thread safe”
  * Can map to: `<threadsafe supported=”false” />`

The addition here is the `memberScope` attribute.

**Comment by mpMelnikov** [comment]
Hi guys!
When you are talking about "tooling that reads ECMAXML" which command in mdoc do you mean?
If it's the "update" command, should we generate <threadsafe> element during generating xml-files from the assembly? If so, what are the rules to determine whether an element is threadsafe or not?

**Comment by joelmartinez** [comment]
@mpMelnikov many engineering groups will write additional utilities (ie. not `mdoc`) that read the EcmaXML, and insert boilerplate documentation that makes sense for their library. A simple example of this kind of usage, could a 3d math library that automatically documents any `float` parameter named `angle`, with boilerplate that clarifies whether it's a `degree` or `radian`.

So in this context, we want to enable this information to be carried in the EcmaXML, but _mdoc_ will not be the one putting it there. We can do this by:

- making the expected modifications in [monodoc-ecma.xsd](https://github.com/mono/api-doc-tools/blob/master/mdoc/Resources/monodoc-ecma.xsd).
- modifying or adding at least one integration test to [mdoc/Makefile](https://github.com/mono/api-doc-tools/blob/master/mdoc/Makefile) that verifies proper validation with `mdoc validate`. You can look at [`check-monodocer-member`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Makefile#L178) for an example of a test that does a validation test. Additionally, check the contribution guidelines for more general information about [writing integration tests](https://github.com/mono/api-doc-tools/blob/master/CONTRIBUTING.md#integration-tests).

**Comment by asokolovskiy15** [comment]
@joelmartinez 
Is it ok if we add `memberScope` as `xs:enumeration`? If so, we can add `static` and `all`, what else should be added?

**Comment by joelmartinez** [comment]
@asokolovskiy15 Yeah, `xs:enumeration` is good. As for the list, I'd imagine that in addition to `static` and `all`, that `instance` would be a useful option? @dend & @TianqiZhang, thoughts?

**Comment by dend** [comment]
@joelmartinez @asokolovskiy15 yes, absolutely support `instance` as another option.
