### ISSUE TITLE
 Parameter name mismatch between syntax and Parameters section

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#116]
During a meeting with the BI team about undocumented API, we discovered that some APIs had a mismatched parameter name between syntax and the parameters section.

For example: https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configuration.getsection?view=netframework-4.7#System_Configuration_Configuration_GetSection_System_String_

Issue is present in the ECMAXML. Because of this mismatch, content for the parameters was not exported from CAPS.

```xml
<MemberSignature Language="C#" Value="public System.Configuration.ConfigurationSection GetSection (string path);" />
<Parameters>
  <Parameter Name="sectionName" Type="System.String" />
</Parameters>
<param name="path">To be added.</param>
```

We have around 3k APIs impacted by this. 

Probably caused by different parameter names used in different assemblies. Tool should pick one to use throughout instead of mixing them (in the example above sometimes it picked the name sectionName and sometimes it picked the name path).

/cc @dend @joelmartinez @meganbradley

**Comment by joelmartinez** [comment]
Unfortunately, if all we do is be consistent with using one of the names, we will lose information. I think we should use a similar solution to #76, where we tag divergent parameter names with `FrameworkAlternate` on which frameworks this name applies to.

**Comment by mairaw** [comment]
That sounds good to me @joelmartinez. I'm guessing then that there is extra engineering work that @dend needs to coordinate to make the build and site understand that, correct?

**Comment by joelmartinez** [comment]
@mairaw precisely, that is correct. There is a batch of changes that is (roughly) next on the roadmap, which address these kind of divergent elements in various frameworks. I'm hoping to address a number of them for each release in that timeframe. Will definitely be a topic of conversation between @dend and I to coordinate other dependencies :)

**Comment by mpMelnikov** [comment]
According to this discussion, did we decide to add the FrameworkAlternate attribute?
- In this case, will we have something like this?
```
<Parameters>
  <Parameter Name="sectionName" Type="System.String" FrameworkAlternate="framework1"/>
  <Parameter Name="path" Type="System.String" FrameworkAlternate="framework2"/>
</Parameters>
```
- Should we add this attribute only in framework mode and only if different names for the same parameter are detected? 
- Do we use ';' as a separator for multiple frameworks?

**Comment by joelmartinez** [comment]
Yes, we'll be using `;` as the separator (per [this comment](https://github.com/mono/api-doc-tools/issues/76#issuecomment-329648961)).

Once I complete my current task, I'm going to be working on this particular issue (along with a few others that require roughly the same solution (conceptually)). It's assigned to me at the moment, so unless something comes up and I'm unable to address it and you guys complete the other tasks, I'll be working on it ... as the solution will require some non-trivial changes to the code.

**Comment by joelmartinez** [comment]
@dend it _was_ going to be #57 ... but I can work on this one next if you'd prefer :)

**Comment by dend** [comment]
@joelmartinez ah yes, let's start with #57, and then jump to this.

**Comment by dend** [comment]
@joelmartinez this should also apply to "implements" information, per a recent conversation with @mairaw. The test case here is that [LinkedList<T>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.linkedlist-1?view=netframework-4.5), that implements `IReadOnlyCollection<T>` in .NET Framework 4.7.1 but not on 4.5.

**Comment by joelmartinez** [comment]
@dend ok ... that will obviously delay the delivery of this feature a tiny bit, but I should be able to finish/release it later this week :) 

do you want a release with some of the other pending features (such as F# sigs) in the meantime?

**Comment by dend** [comment]
@joelmartinez yes, I think that it would be good to get an earlier release so that we can integrate it in our CIs and see if there are any issues before we pile up more features in 😄 

Finishing the release with this bug resolved by end of week sounds great as well!

**Comment by joelmartinez** [comment]
Just to follow up on the implementation ... there are three changes being made in the scenario when a method diverges across frameworks only by parameter name (which means that the `docid` will be the same for both of them). This is an example of a `<Member>` node which exhibits this from the unit tests:

```xml
<Member MemberName="Meth">
      <MemberSignature Language="C#" Value="public void Meth (int a, string b, int c);" FrameworkAlternate="One;Three" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig instance void Meth(int32 a, string b, int32 c) cil managed" FrameworkAlternate="One;Three" />
      <MemberSignature Language="C#" Value="public void Meth (int a, string d, int c);" FrameworkAlternate="Two" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig instance void Meth(int32 a, string d, int32 c) cil managed" FrameworkAlternate="Two" />
      <MemberType>Method</MemberType>
      <AssemblyInfo>
        <AssemblyName>DocTest-frameworkalternate-one</AssemblyName>
        <AssemblyVersion>0.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>DocTest-frameworkalternate-two</AssemblyName>
        <AssemblyVersion>0.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Void</ReturnType>
      </ReturnValue>
      <Parameters>
        <Parameter Name="a" Type="System.Int32" Index="0" />
        <Parameter Name="b" Type="System.String" Index="1" FrameworkAlternate="One;Three" />
        <Parameter Name="d" Type="System.String" Index="1" FrameworkAlternate="Two" />
        <Parameter Name="c" Type="System.Int32" Index="2" />
      </Parameters>
      <Docs>
        <param name="a">To be added.</param>
        <param name="b">To be added.</param>
        <param name="d">To be added.</param>
        <param name="c">To be added.</param>
        <summary>To be added.</summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
```

- a `FrameworkAlternate` attribute is added to the affected parameter (in this case, the second `string` parameter of the method). 
- an `Index` attribute was added to all `Parameter` nodes ... this simplifies record keeping to make sure they are presented in the correct order (before, a parameter's index was assumed based on its position as a child of the `Parameters` node.
- and lastly, all `Parameter` entries will have a corresponding `param` with a matching `name` attribute. 

So, all of the above items need to be taken into account when it comes to displaying the information. If there are no `FrameworkAlternate` entries, then all parameter names match. If the attribute exists, then the list of parameters needs to be filtered accordingly, and displayed per the order in the `Index` attribute.
