### ISSUE TITLE
Some unit tests fail on Windows

### ISSUE THREAD

**Issue by mpMelnikov** [mono/api-doc-tools#125]
CountTypeGenericArgumentsTest:
`
System.Security.SecurityException : Invalid assembly public key. (Exception from HRESULT: 0x8013141E)
`
CountTypeGenericArgumentsTest_Nested:
`
System.Security.SecurityException : Invalid assembly public key. (Exception from HRESULT: 0x8013141E)
`
DocPathConfigTest:
`
  Expected: not null
  But was:  null
`

**Comment by joelmartinez** [comment]
These issues seem to stem from behavioral differences between the mono and .net 4.5 framework implementations. I'm working now to normalize those so that they work both on mac/Linux and windows.
