### ISSUE TITLE
[mdoc] Support VB.NET signatures

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#131]
Support API entity signatures in Visual Basic.

**Comment by joelmartinez** [comment]
VB.NET Language Reference: https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/

**Comment by mpMelnikov** [comment]
@joelmartinez 
We've tested the first version of VBMemberFormatter on the dll-file compiled from DocTest-v1.cs. Also, we've manually translated DocTest-v1.cs into Visual Basic. Comparing the results we have some questions.
1. What is a better approach to deal with `static class`? Should it be a `Module` or a `Sealed Class` with `Shared` members?
2. There is no support for a `dynamic` keyword in the VB.NET. So, we have such results now:
```
// Input C# code
public delegate dynamic D (Func<string, dynamic, object> value);
```
```
' Output VB code
Public Delegate Function D(value As Func(Of String, Object, Object)) As Object
```
Is it an appropriate approach?
3. There is no support for attributes for generic parameter and on return in VB. But it seems that CSharpFormatter ignores them either:
```
// Input C# code
public U BaseMethod<[Doc ("S")] S> (S genericParameter) 
```
```
<!-- Output xml -->
<MemberSignature Language="C#" Value="public U BaseMethod&lt;S&gt; (S genericParameter);" />
<MemberSignature Language="ILAsm" Value=".method public hidebysig instance !U BaseMethod&lt;S&gt;(!!S genericParameter) cil managed" />
<MemberSignature Language="VB" Value="Public Function BaseMethod(Of S) (genericParameter As S) As U" />
```
Is it ok?
5. There is no support for unmanaged code in VB .NET. So, we can't translate this code into VB.NET:
`public unsafe int *pCount;`. What should we do in this a case? Maybe we should display something like "this feature is not supported"?

4. It seems that CSharpFormatted ignores `protected internal` keyword
```
// C# input:
protected internal const double PI = 3.14159;
```
```
<!-- xml output: -->
      <MemberSignature Language="C#" Value="protected const double PI = 3.14159;" />
```
Should it be like this? 
```
      <MemberSignature Language="C#" Value="protected internal const double PI = 3.14159;" />
      <MemberSignature Language="VB" Value="Protected Friend Const PI As Double  = 3.14159" />
```
5. As VB .NET is not a case-sensitive language, this code can't be compiled:
`    Public Function SomeFunction(Of T) (t As T) As Integer`. But IL code of assembly can contain such names. So, how should we deal with it? Detect this situation and rename variables?
6. Is it a correct translation from C# into VB?
```
        Public Iterator Function ToEnumerable(Of T)(self As T) As IEnumerable(Of T)
            Yield self
        End Function
```
We're a little confused by [this MSDN example](https://msdn.microsoft.com/en-us/library/bb335435(v=vs.110).aspx?cs-save-lang=1&cs-lang=vb#code-snippet-1), where `As IEnumerable(Of TSource)` constraint is added for VB.

**Comment by joelmartinez** [comment]
@mpMelnikov Great questions! _please note_, the numbering of the questions in your comment were a little off, so I've answered them in the order they were asked below.

1. I would go with a `NotInheritable` class in vb when you encounter a static class
2. Yes, as far as I know, `Object` would be the correct response here ... my assumption is that if the user wants to use `dynamic` programming, they will turn `Option Strict Off`.
3. To maintain consistency, yes that's ok ... but please open another github issue to fix the fact that our formatters are ignoring generic parameter attributes. We can fix them all together there.
4. If you write an `unsafe` method with a pointer in C#, can you consume that function at all from VB.NET?
    - If the answer is "yes", then I'd assume that you would represent `int *` with something like an `IntPtr` ... I don't know this to be a fact, just a guess that you can check on.
    - If the answer is "no", then you should add a `public virtual bool IsSupported (TypeReference tref) => true;` and `public virtual bool IsSupported (MemberReference mref) => true;` to the `MemberFormatter` class ... that way, the vb formatter can override that to check for the pointer in a member, and avoid outputting the `MemberSignature` entry entirely (ie. call `.IsSupported` before you get the signature and write the vb.net signature XML.
5. Hmm, it probably _should_ be using the `protected internal` keywords. Please open a github issue on the fact that the C# formatter is not outputting this keyword. But yes, the VB signature looks correct.
6. This looks like a minefield of compatibility ... Similar to my answer for # 4, can a function like that written in C# be consumed at all in VB.NET? if the answer is no, then I would give a similar proposal, to add logic to the new `IsSupported` function of the vb formatter, and simply avoid outputting the XML entirely. You should also take into account other situations, such as multiple parameters, all containing differently cased named parameters (works in C#, not in VB.NET).
7. Yes that looks correct to me. As you can see from the [vb.net language reference](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/function-statement), `As returntype` simply defines the return type of the function explicitly. In this case, the return type is `IEnumerable<T>` :)

One additional note ... I noticed that you're using "VB" as the `Language` attribute value. Should we use `VB.NET`? @dend ?

**Comment by joelmartinez** [comment]
Also, another requirement that I mentioned in [another comment](https://github.com/mono/api-doc-tools/issues/132#issuecomment-337608829). 

> Additionally, I should mention one more requirement that we probably haven't discussed in these various language/signature items ... the only default signature formatters are ILASM and C#. We have already added `docid`, which can be triggered by passing [`--use-docid`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L198) on the CLI. I would like to generalize this so that we can use a new CLI parameter called `-lang F#`, `-lang C++/CLI`, etc, to add the additional signature formatters. For backwards compatibility, `--use-docid` should still work (probably just call the same function as the new `-lang` parameter with `docid` as the argument).

**Comment by dend** [comment]
@terrajobst @richlander do we call the current VB as just Visual Basic, or Visual Basic .NET? We want to make some changes to the current doc generation pipeline and want to use a brand-approved language shorthand.

**Comment by mpMelnikov** [comment]
@joelmartinez Thank you for such detailed answers!
4. In VB.NET I can instantiate type with unsafe members, but I can not call unsafe members:
```
        Dim widget1 As Widget = New Widget("some_string") 'It's ok
        Dim pCount = widget1.pCount; 'Can't be compiled. BC30656 Field is of an unsupported type.
```
So, we go to the second plan (`IsSupported` method).
6. There is no problem to use this method in VB.NET:
```
// C#
public void MethodWithNamedParameters(int someName, int soMeNaMe, SomeClass someClass)
```

```
' VB.NET
Dim someClass1 As SomeClass = New SomeClass()
someClass1.MethodWithNamedParameters(12, 3, New SomeClass())
```
Moreover, Visual Studio hints VB.NET signature which can't be really compiled:
![image](https://user-images.githubusercontent.com/7716624/31768337-a1b23740-b4d7-11e7-9551-da6c2eb9c569.png)

**Comment by joelmartinez** [comment]
Ahh I see ... that's a goodpoint that you can still call the method with VB. However, since the signature that mdoc would output would not be compilable, I recommend going with the same solution of avoiding the output of the VB.NET signature entirely.
