### ISSUE TITLE
[mdoc] Support for JavaScript signatures

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#133]
Support API entity signatures in JavaScript.

### Exception 1:

For the V1 Pri1 implementation, we will not implement custom “retrievers”.  If a non-static class doesn’t have a public constructor (in other words, it is not possible to automatically determine the call to instantiate an instance of the class), the Javascript syntax should either:

* show a standard disclaimer such as:
“This class does not provide a public constructor” or
“See the remarks section for information on obtaining an instance of this class”
* Give a degenerate declarative syntax, such as simply: “Windows.System.FolderLauncherOptions” for the FolderLauncherOptions class.
The specific solution to use here is still TBD.  If you’re blocked, pick A1 for now.
We will investigate whether a Pri 2 feature to modify the syntax block with custom syntax is necessary.

## How to determine if an API supports JavaScript

Use the `WebHostHidden` attribute. If `WebHostHidden` is present, the API doesn’t support JavaScript. None of the APIs in the “XAML” namespaces support JavaScript. 

#### Usage (get)

```
var [property value type, camel-cased] = [typename, camel-cased].[property name, camel-cased];
```

#### Usage (set)

```
[typename, camel-cased].[property name, camel-cased] = [property value type, camel-cased];
```

#### Usage (get)

```
var [property value type, camel-cased] = [typename].[property name, camel-cased];
```

#### Usage (set): 

```
[typename].[property name, camel-cased] = [property value type, camel-cased];
```

**Note:** property value might vary between JavaScript, C# and C++. Use the same filtering behavior that is used for C# and C++. 

#### FolderLauncherOptions.DesiredRemainingView property 

Specifies how much space on the screen to leave for the calling app when launching File Explorer. The calling app can take up more or less space than File Explorer, or File Explorer can fill the entire screen.
##### Syntax

**JavaScript (usage)**
```
var viewSizePreference = folderLauncherOptions.desiredRemainingView;
folderLauncherOptions.desiredRemainingView = desiredRemainingView;
```

**C#**

```
public ViewSizePreference DesiredRemainingView { get; set; }
```

**VB**
```
Public Property DesiredRemainingView As ViewSizePreference
```

**C++**

```
public:
property ViewSizePreference DesiredRemainingView { 
   ViewSizePreference get();
   void set (ViewSizePreference value);
}
```

**Property value**
Type: `ViewSizePreference`
One of the enumeration values that specifies how much space on the screen to leave for the calling app when launching File Explorer. 

### Enums

Usage syntax

```
var value = [fully qualified type].[camel-cased name of first enum value];
```

**Note:** member names for JavaScript should be camel-cased. 

##### ProcessorArchitecture enumeration

Specifies the processor architecture supported by an app.

**Syntax**

**JavaScript**

```
var value = Windows.System.ProcessorArchitecture.x86;
```

**C#**

```
public enum ProcessorArchitecture
```

**VB**

```
Public Enum ProcessorArchitecture
```

**C++**

```
public enum class ProcessorArchitecture
```

**Members**
The ProcessorArchitecture enumeration has these members.

|Member|	Value|Description
|-----|------|-----|
|X86 \| x86 |0|The x86 processor architecture.|
|Arm \| arm|5|The ARM processor architecture.|
|X64 \| x64|9|The x64 processor architecture.|
|Neutral \| neutral|11|A neutral processor architecture.|
|Unknown \| unknown|65535|An unknown processor architecture|

### Async Methods

(For static methods, use the fully-qualified class name. For non-static, use the class name without qualification and camel-cased.)

Usage: 

```
[fully qualified type name].[camel-cased method name]([parameter names]).done( /* Your success and error handlers */ );
```

**Note:** parameter and return types might be different from C#. Need to provide new type mapping. 

**Launcher.FindUriSchemeHandlersAsync(String, LaunchQuerySupportType) method**

Enumerate the scheme handlers on the device.

**Syntax**

**JavaScript (usage)**

```
Windows.System.Launcher.findUriSchemeHandlersAsync(scheme, launchQuerySupportType).done( /* Your success and error handlers */ );
```

**C#**

```
public static IAsyncOperation<IReadOnlyList> FindUriSchemeHandlersAsync(
  string scheme, 
  LaunchQuerySupportType launchQuerySupportType
)
```

**VB**

```
Public Shared Function FindUriSchemeHandlersAsync(
  scheme As String,  
  launchQuerySupportType As LaunchQuerySupportType 
) As IAsyncOperation(Of IReadOnlyList)
```

**C++**

```
public:
static IAsyncOperation<IVectorView>^ FindUriSchemeHandlersAsync(
  String^ scheme, 
  LaunchQuerySupportType launchQuerySupportType
)
```

**Parameters**

`scheme` 

Type: `String [JavaScript] | System.String [.NET] | Platform::String [C++]`

The scheme name that you find to find handlers for. For example, "ms-lens".

### Methods

**Non-static**

**Usage (not void)**

```
var [return type, camel-cased] = [class-name, camel-cased].[method-name, camel-cased]([parameter name list]);
```

**Usage (void)**

```
[class-name, camel-cased].[method-name, camel cased]([parameter name list]);
```

**Static**

**Usage (not void)**

```
var [return type, camel-cased] = [fully-qualified class-name].[method-name, camel-cased]([parameter name list]);
```

**Usage (void)**

```
[fully-qualified class name].[method-name, camel cased]([parameter name list]);
```

**Example**

**MemoryManager.TrySetAppMemoryUsageLimit method**

Tries to set a specific memory cap for the current app or task. In cases where memory caps are shared between foreground and background components, any difference between the default cap and the new request will be assigned to the other component.

**Syntax**

**JavaScript (usage)**

```
var boolean = Windows.System.MemoryManager.trySetAppMemoryUsageLimit(value);
```

**C#**

```
public static bool TrySetAppMemoryUsageLimit(
  ulong value
)
```

**VB**

```
Public Shared Function TrySetAppMemoryUsageLimit(
  value As ULong 
) As Boolean
```

**C++**

```
public:
static bool TrySetAppMemoryUsageLimit(
  unsigned long long value
)
```

**Parameters**

`value`
 
Type: `Number [JavaScript] | System.UInt64 [.NET] | uint64 [C++]`

The new memory limit to set.

**Return value**

Type: `Boolean [JavaScript] | System.Boolean [.NET] | Platform::Boolean [C++]`

True if the operation succeeded; otherwise, false.

### Events
Usage: 

```
function on[EventName](eventArgs){/* Your code */}
[class name, camel cased].addEventListener(“[event name, camel cased]”, on[EventName]); 
[class name, camel cased].removeEventListener(“[event name, camel cased]”, on[EventName]);
```

•	If the event supports property syntax (it has a corresponding EventName property), add this:

```
- or -
[class name, camel cased].on[event name, all lower-case] = on[EventName];
```

**Example**

**MemoryManager.AppMemoryUsageIncreased event**

Raised when the app's memory consumption has increased to a higher value in the AppMemoryUsageLevel enumeration.

**Syntax**

**JavaScript (usage)**

```
function onAppMemoryUsageIncreased(eventArgs) { /* Your code */ }
 
// addEventListener syntax
memoryManager.addEventListener("appmemoryusageincreased", onAppMemoryUsageIncreased);
memoryManager.removeEventListener("appmemoryusageincreased", onAppMemoryUsageIncreased);
```
- or -
```
memoryManager.onappmemoryusageincreased = onAppMemoryUsageIncreased;
```

**C#**

```
public static event EventHandler<object> AppMemoryUsageIncreased
```

**VB**

```
Public Shared Event AppMemoryUsageIncreased As EventHandler(Of Object)
```

**C++**

```
public:
static event EventHandler<object>^ AppMemoryUsageIncreased {
   Windows::Foundation::EventRegistrationToken add(EventHandler<object>^ value);
   void remove(Windows::Foundation::EventRegistrationToken token);
}
```

**Event information**

**Delegate** 

EventHandler [JavaScript] | System.EventHandler<Object> [.NET] | Windows.Foundation.EventHandler<Object> [C++]

### Structures

**Usage**

```
var [struct name, camel cased] = {
	[fieldname, came cased] : /* Your value */
}
```

**Example**

```
var rect = {
    height : /* Your value */,
    width: /* Your value */,
 
    x: /* Your value */, 
    y: /* Your value */
}
```

https://docs.microsoft.com/en-us/uwp/api/windows.foundation.rect  

### Delegates

**Usage**

```
var [delegateName, camel-cased]Handler = function([parameter name list, camel cased]){
  /* Your code */
}
```

**Example:**

```
var asyncActionCompletedHandler = function(asyncInfo, asyncStatus) {
 /* Your code */
}
```

https://docs.microsoft.com/en-us/uwp/api/windows.foundation.asyncactioncompletedhandler 

### Interfaces

**Usage (missing retrievers)**

```
// You can’t instantiate an interface directly in JavaScript. You can use objects that implement the interface, however. 
```

Retrievers for interfaces and types without constructors (factory pattern)
Consider adding a dedicated “retrievers” section that tell readers how to retrieve an instance of interfaces and classes that don’t have a public constructor.

**Comment by joelmartinez** [comment]
another requirement that I mentioned in [another comment](https://github.com/mono/api-doc-tools/issues/132#issuecomment-337608829). 

> Additionally, I should mention one more requirement that we probably haven't discussed in these various language/signature items ... the only default signature formatters are ILASM and C#. We have already added `docid`, which can be triggered by passing [`--use-docid`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L198) on the CLI. I would like to generalize this so that we can use a new CLI parameter called `-lang F#`, `-lang C++/CLI`, etc, to add the additional signature formatters. For backwards compatibility, `--use-docid` should still work (probably just call the same function as the new `-lang` parameter with `docid` as the argument).

**Comment by katebialiatka** [comment]
Hello,

@joelmartinez We have several questions in regards to this issue:
1) As we can see, JS examples contains only 'Usage' examples. Does it mean that we need to add only one formatter which generates usage signatures?
2) Is it possible to see working examples of JS code on MSDN?
As we can see, now JS examples contain` '// You can use this class in JavaScript.' `string. See example on the [link ](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.contacts.dataprovider.contactlistsyncmanagersyncrequest).
3) The ticket description does not contain reference for generics. Are generics supported here? Do you probably have any relevant info?
4)  The ticket description contains description for type members only. Should we generate signature for a type itself?

**Comment by joelmartinez** [comment]
@katebialiatka as discussed earlier, we're going to wait for @dend to get some feedback from the team on this. And I'll restate my default position (just for the sake of clarity) ...

The signature formatter values are currently meant to represent how you would *define* a given construct (type or member) in the target language. So far, we have one exception to this rule for F#, where the functional programming community has [different expectations](https://github.com/mono/api-doc-tools/issues/108#issuecomment-341772570). 

F# has also initially requested usage samples, but for now that has been pushed off (afaik) ... we discussed some potential implementations there, such as adding an additional attribute to the `TypeSignature` and `MemberSignature` nodes; something like `... Usage="blah.blah()" />`. So when we implement usage signatures, I'd like to go in that direction. The only issue is that too much of the code and pipeline will be expecting the `Value` attribute to be there, so we wouldn't be able to implement an "only-usage" signature.

**Comment by mpMelnikov** [comment]
I'd like to add one more question:
6. Which version of JavaScript should we use? ECMAScript 5? ECMAScript 2015? Something else?

**Comment by joelmartinez** [comment]
@mpMelnikov good question. I couldn't find any detailed information on that in [the docs](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-js-apps) ... in fact, I couldn't really find any information about the low level implementation/support of js. 

On this page (http://try.buildwinjs.com/), I tried using an ES6 feature (`let`), and it did not work, so presumably, we know it doesn't support ES6?

@dend, can you connect us with a subject matter expert here?

**Comment by dend** [comment]
@joelmartinez started a thread. In the meantime, I think it's worth focusing on other items that are not JS support, that are more hi-pri. This item here is an enhancement, and while we want it for M3, it would not be the end of the world if it ships later, given the scope of work.

cc: @katebialiatka @mpMelnikov
