### ISSUE TITLE
[mdoc] Update assembly information on re-runs

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#135]
When `mdoc` runs over existing content, it needs to update the assembly information, including for cases where an assembly was removed and is no longer in the reflection chain. The same applies to assembly versions.

The very basic validation scenario here, at least in frameworks mode, is to check whether there is the same `DocID` in a frameworks file, that is inside a generated XML file - if that is not the case, remove the member/type from the generated file.

**Comment by joelmartinez** [comment]
Would be convenient to work on this along with #147
