### ISSUE TITLE
C# formatter is not outputting "protected internal"

### ISSUE THREAD

**Issue by mpMelnikov** [mono/api-doc-tools#137]
Based on #131 discussion
CSharpFormatter is outputting "protected" instead of "protected internal". Can be reproduced on the assembly compiled from mdoc/Test/DocTest-v1.cs file.
1. csc DocTest-v1.cs /unsafe
2. mdoc update -o en DocTest-v1.dll
```
// C# input:
protected internal const double PI = 3.14159;
```
```
<!-- xml output: -->
<MemberSignature Language="C#" Value="protected const double PI = 3.14159;" />
```

**Comment by joelmartinez** [comment]
@dend this was a pre-existing bug discovered during development. Do we want to make this a part of milestone#3, or address at a later date?

**Comment by dend** [comment]
@joelmartinez let's make this part of M3 - this seems to be data loss.
