### ISSUE TITLE
`mdoc update` performs ad hoc API doc history curation based on "To be added."

### ISSUE THREAD

**Issue by MichaelNorman** [mono/api-doc-tools#168]
In response to https://github.com/xamarin/documentation/issues/2362, we seem to have learned that `mdoc update` removes deleted APIs IFF they have not been authored prior to when `mdoc` discovers that they've been deleted. _This leaves a policy decision about history hard-coded into a tool that only considers the current state of the product as embodied in the DLL that it was most recently passed._ Currently, our web layer does not enable version filtering on the documentation, resulting in extraneous topics and visual clutter on type landing pages.

Here are some suggested remedies, in decreasing order of personal preference:

1. Preserve the existing default behavior, and add two switches, one to always preserve existing content, and another to preserve only APIs and content that correspond to the assembly/dll that was passed to `mdoc update`. In this way, teams can rely on their current processes, and the adopt a coherent and explainable policy in the near term, either preserving everything or moving history curation to an external tool. `--preserve-default`, `--preserve-all`, and `--preserve-none` suggest themselves as good switch names, and the absence of a switch indicating `--preserve-default`.

2. Always preserve. In other words, curate history conservatively, allowing teams to cull/sort old items externally, if desired.

3. Never preserve. In other words, force external history curation.

In the nice-to-have column: Product versions, in addition to assembly versions. (Perhaps from a manually maintained correspondence table.)

**Comment by joelmartinez** [comment]
@MichaelNorman ... if the display/front-end *by default* includes a version picker which defaults to the latest version, would it satisfy the need for this?

**Comment by joelmartinez** [comment]
going to close this due to the fact that product reference should be using monikers now, so this kind of issue is mitigated by the reference maintaining older monikers in the binary repository, thus ensuring that members removed in subsequent versions will not be deleted
