### ISSUE TITLE
Support <img src=""/>

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#171]
Currently in the schema, the `img` tag only supports `href` - this likely works well for legacy XSLT-based systems, but breaks HTML renderers without transforms. We'd like to just have a safe default for this particular scenario.

**Comment by joelmartinez** [comment]
Would be good to implement this along with #169

**Comment by dend** [comment]
Just a heads-up that this is not a blocker, as @TianqiZhang has implemented the proper transform on the docs.microsoft.com side.
