### ISSUE TITLE
Versioning Story

### ISSUE THREAD

**Issue by joelmartinez** [mono/api-doc-tools#19]
Originally, when this project was a part of the mono project ... the version number was bound to the version of the mono framework/runtime. As will now be moving to out-of-band releases for mdoc, we have to establish a new version number. 

[Consts.cs](/mono/api-doc-tools/tree/master/mdoc/Consts.cs) holds the version number that is reported when you `mdoc --version`. 

The released/stable version at the time of this project being extracted into this repository was `4.6`. I propose that, for the sake of moving cleanly to a new version ... the next release be versioned as `5.0`, and propose that this version change go out with https://github.com/mono/api-doc-tools/pull/18

Thoughts?

**Comment by dend** [comment]
Sounds good.
