### ISSUE TITLE
Encoded tags in comments disappeared in ECMAXML

### ISSUE THREAD

**Issue by TianqiZhang** [mono/api-doc-tools#192]
In the source code, there's some encoded tags:
https://github.com/aspnet/Razor/blob/bdbb854bdbde260b3c70f565a93ebbb185a7c5a7/src/Microsoft.AspNetCore.Razor/TagHelpers/TagStructure.cs#L17-L20

However in the generated ECMAXML, the tags are gone:
https://github.com/aspnet/ApiDocs/blob/live/api/xml/Microsoft.AspNetCore.Razor.TagHelpers/TagStructure.xml

This is reported by https://github.com/dotnet/docfx/issues/2318

**Comment by dend** [comment]
The content is there in the ECMAXML - you might be looking at the wrong element. It seems like the content is missing either in the YAML or the template does not interpret those.

**Comment by TianqiZhang** [comment]
@dend yes you are right, closing this one.
