### ISSUE TITLE
[Q] Repetitive elements

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#197]
This question is driven primarily by curiosity, but also by the fact that `mdoc` today can insert dupe things into documents on import.

Looking [at the schema](https://github.com/mono/api-doc-tools/blob/master/mdoc/Resources/monodoc-ecma.xsd#L262), it seems that a single `Docs` element allows `unbounded` things such as:

* `summary`
* `returns`
* `value`
* `threadsafe`
* `forInternalUserOnly`

It feels, at least in theory, that for every API entity, we would only have one of each, and not open the doors for many instances.

What is the rationale behind having these under `unbounded`?

**Comment by jonpryor** [comment]
> What is the rationale behind having these under `unbounded`?

I didn't know -- and still don't know -- how to express that construct in XSD. :-)

The original XSD was hand-translated from the [ECMA-335](https://www.ecma-international.org/publications/standards/Ecma-335.htm) DTD, which contains:

```xml
<!ELEMENT Docs (
    (summary?, altmember?, altcompliant?, typeparam*, param*, returns?, value?, exception*, threadsafe?, remarks?, example?, permission?)
  | (typeparam*, param*, summary?, altmember?, altcompliant?, returns?, value?, exception*, threadsafe?, remarks?, example?, permission?)
  | (summary?, altmember?, altcompliant?, typeparam*, param*, returns?, value?, remarks?, threadsafe?, exception*, example?, permission?)
  | (typeparam*, param*, summary?, altmember?, altcompliant?, returns?, value?, remarks?, threadsafe?, exception*, example?, permission?)
)>
```

Suggestions on how to properly express that in XSD are welcome. :-)

**Comment by joelmartinez** [comment]
I'm going to close this issue for now, as it's represented in another issue that we tackled about a year ago ... it was closed at the time, but it will probably be re-opened as it's still an open issue:
https://github.com/mono/api-doc-tools/issues/180
