### ISSUE TITLE
Tuple class representation is incorrect

### ISSUE THREAD

**Issue by cartermp** [mono/api-doc-tools#206]
![image](https://user-images.githubusercontent.com/6309070/35706858-40f6bd18-075c-11e8-9288-7b440e9982f0.png)

Note that this is incorrect syntax for F#, and the correct representation would actually be what we have on MSDN: https://msdn.microsoft.com/en-us/library/dd387185

**Comment by dend** [comment]
@joelmartinez this is a blocker and we should address it in our MSDN migration battle plan.

cc: @cartermp @MairaWenzel

**Comment by joelmartinez** [comment]
Just for simplicity, pasting in the MSDN signature here:

```fsharp
[<SerializableAttribute>]
type Tuple<'T1, 'T2, 'T3, 'T4, 'T5, 'T6, 'T7> = 
    class
        interface IStructuralEquatable
        interface IStructuralComparable
        interface IComparable
        interface ITuple
    end
```
Does this expected notation extend to *every* generic type + interface implementation? or is `Tuple` somehow different from other generic types?

**Comment by cartermp** [comment]
@joelmartinez Tuples are a special case in the compiler (cc @dsyme):

```fsharp
let tup: int * int * string = (1, 2, "hello")
```

However, for generic classes this syntax is used:

```fsharp
type C<'T1, 'T2, 'T3> =
    ...
    interface IFoo with
        ...
    interface IBar with
        ...
```

With verbose syntax, the `class ... end` syntax is used. I'm fine with showing what we have with MSDN for now and then finding ways to simplify from there, though.

**Comment by joelmartinez** [comment]
re-opening this per reported remaining issue ... will let @cartermp fill in the details :)

**Comment by cartermp** [comment]
There's a remaining issue with this, but I don't think it's tuple-specific. I'll raise another issue.
