### ISSUE TITLE
[mdoc] Some types are missing if I run a lot of dlls together

### ISSUE THREAD

**Issue by TianqiZhang** [mono/api-doc-tools#21]
Not sure if you’ve noticed, when running mdoc against all dlls of .Net 4.6.2, some types are not saved into xml file. I used this folder: \\fxcore\Platforms\ApiCatalog\.NET Framework 4.6.2 and copied *.dll to another folder.

For example, if you run “mdoc update -o xmlFolder mscorlib.dll”, you’ll get 22 xml files under System.Collections.Generic folder. However if you use the command from [run.sh.txt](https://github.com/mono/api-doc-tools/files/776168/run.sh.txt) to run against all dlls, you get only 20 xml files in the same folder. From below image you can see the two lists of files are almost entirely different:
![typesmissing](https://cloud.githubusercontent.com/assets/5326582/22962718/b6bf70ea-f389-11e6-86df-90eb158367d5.png)

**Comment by joelmartinez** [comment]
@dend can you see if this issue is still present using the latest release?

**Comment by dend** [comment]
I have tested this in the latest release and don't see this. @TianqiZhang I will send updated instructions, would be great to know if you can repro this ASAP.

**Comment by joelmartinez** [comment]
gonna close this unless we hear back that it's still present :)
