### ISSUE TITLE
[mdoc] Special treatment of ref-like structs to not produce Obsolete attribute

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#225]
Example: https://docs.microsoft.com/en-us/dotnet/api/system.span-1

`Span<T>` is a new type, however, it's displaying an Obsolete attribute in its signature on docs:
![image](https://user-images.githubusercontent.com/12971179/38576430-fbe81df2-3cb2-11e8-8800-81f9905d0be6.png)

This is due to how ref-like structs metadata is represented:
https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/span-safety.md#metadata-representation-or-ref-like-structs

As @weshaggard pointed out: we need to special case the obsolete message or you can special case any obsolete attribute with the specific text. This is what the .NET team does with their tools https://github.com/dotnet/buildtools/blob/master/src/Microsoft.Cci.Extensions/Writers/CSharp/CSDeclarationWriter.Attributes.cs#L399.

**Comment by joelmartinez** [comment]
This issue is conceptually similar to #212, in the sense that it involves special-casing metadata.
