### ISSUE TITLE
[Bug] Incorrect signatures generated for return types

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#230]
In [System.ReadOnlySpan`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/ReadOnlySpan%601.xml), the ReadOnlySpan<T>.Item property. The <ReturnType> element is  
 
`<ReturnType>System.T&amp;</ReturnType>`
 
For similar Item properties of generic types (such as List<T>.Item), it appears as:
 
`<ReturnType>T</ReturnType>`

In [System.ReadOnlySpan~1+Enumerator.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/ReadOnlySpan%601%2BEnumerator.xml), the ReadOnlySpan<T>+Current property. The <ReturnType element is again:
 
`<ReturnType>System.T&amp;</ReturnType>`
 
and the property type doesn’t appear in the documentation.

**Comment by joelmartinez** [comment]
@asokolovskiy15 ok, a few things to consider:

- Look at [this code](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L3601) ... it seems relevant to this discussion.
- What exactly is it about the `DangerousGetPinnableReference` member, that's causing the `@` to be added to the return type? 
- Does this have anything to do with generic [covariance](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out-generic-modifier) and [contravariance](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-generic-modifier)? If so, this is a feature we need to add at some point ... I couldn't find a GH issue that references this.

In any case, it's good that we're no longer printing the namespace on these generic types, but I think it's more important for us to understand why this extra character is being added, in order for us to figure out the best way to handle it. For example, if it's critical information to know, I'd probably prefer that we add the information about what it is to an attribute. We can then use this in the documentation enumerator (where we match XML nodes to `MemberDefinition`s).

**Comment by asokolovskiy15** [comment]
@joelmartinez 
After investigation of this issue, we've come to the conclusion that `@` and `&` are added if signature contains `ref` keyword. If return type is readonly symbol `&` is added. This applies not only to generic parameters.
For covariance or contravariance, there is special element for this case:

`<ParameterAttribute>Covariant</ParameterAttribute>`
`<ParameterAttribute>Contravariant</ParameterAttribute>`

How should we handle this case? We can add attributes both for `ref` and for `readonly` keywords. It will look like this
```
<ReturnValue>
      <ReturnType  IsRefType="true" IsReadonlyType="true">System.Int32</ReturnType>
</ReturnValue>
```

Also, please note [this issue](https://github.com/mono/api-doc-tools/issues/249). As we can see signature doesn't contain `ref` and `readonly` keywords. Should we fix it?

**Comment by joelmartinez** [comment]
@asokolovskiy15 good catch ... I would follow the existing convention of using the `RefType` attribute (example [here](https://github.com/mono/api-doc-tools/blob/f51d2af552e63de7d72555a5c61d9c2a28b7faa0/mdoc/Test/en.expected-operators/mdoc.Test.SampleClasses/TestClass.xml#L658-L659)).

```xml
      <Parameters>
        <Parameter Name="a" Type="System.Int32&amp;" RefType="ref" />
        <Parameter Name="b" Type="System.Int32&amp;" RefType="out" />
      </Parameters>
```

So in this case, I'd add `RefType` to the XSD, and have a `ref` value, and a `readonly` value. Again, making sure that the documentation enumerator will correctly match this for overloads and such, on a subsequent run on existing EcmaXML.

As for that other gh issue ... yes that would be wonderful to fix that one as well. We'd have to run it by @dend first from a project plan perspective :)

**Comment by joelmartinez** [comment]
This GH issue will be resolved with this PR: https://github.com/mono/api-doc-tools/pull/251
