### ISSUE TITLE
[performance] Depending on the working directory, mdoc takes years

### ISSUE THREAD

**Issue by mattleibow** [mono/api-doc-tools#232]
I am trying to run mdoc for SkiaSharp and all my commands are run from the root directory.

This bit of code takes a very long time that I stopped it after a few minutes:
https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/Updater/Frameworks/MDocResolver.cs#L107-L114

I see the `SearchDirectory` method is passed a list of directories, namely the "." directory - this means that it will scan over 7.5K folders and look at (probably) 45K files...

To work around this, I just set my working directory to the docs folder, but it was a bit annoying.

**Comment by mattleibow** [comment]
I am going to have a look at this chunk of code that is slow and see what I can do to make it 🚀 
https://github.com/mono/api-doc-tools/blob/mdoc-5.6.4/mdoc/Mono.Documentation/Updater/Frameworks/MDocResolver.cs#L104-L136

**Comment by joelmartinez** [comment]
This was included in this release: https://github.com/mono/api-doc-tools/releases/tag/mdoc-5.6.5
