### ISSUE TITLE
Incorrect MemberSignatures for ref returns and ref readonly returns

### ISSUE THREAD

**Issue by svick** [mono/api-doc-tools#249]
Consider the following C# 7.2 code:

```c#
public class C
{
    int i;

    public ref int Ref() => ref i;
    public ref readonly int ReadonlyRef() => ref i;
}
```

When I generate XML for it using `mdoc update -o en lib.dll`, the relevant parts of the output are:

```xml
<Member MemberName="ReadonlyRef">
  <MemberSignature Language="C#" Value="public Int32&amp; ReadonlyRef ();" />
  <MemberSignature Language="ILAsm" Value=".method public hidebysig instance class System.Int32&amp; modreq(System.Runtime.InteropServices.InAttribute) ReadonlyRef() cil managed" />
  <ReturnValue>
    <ReturnType>System.Int32&amp;</ReturnType>
  </ReturnValue>
</Member>
<Member MemberName="Ref">
  <MemberSignature Language="C#" Value="public int Ref ();" />
  <MemberSignature Language="ILAsm" Value=".method public hidebysig instance int32 Ref() cil managed" />
  <ReturnValue>
    <ReturnType>System.Int32@</ReturnType>
  </ReturnValue>
</Member>
```

The fact that `ReturnType` for `Ref` contains `@` has already been mentioned in https://github.com/mono/api-doc-tools/issues/230.

But what this issue is about are the `MemberSignature`s. I believe the member signatures for C# should use C# syntax for the two methods. That is, they should be:

```xml
<MemberSignature Language="C#" Value="public ref readonly int ReadonlyRef ();" />
<MemberSignature Language="C#" Value="public ref int Ref ();" />
```

**Comment by dend** [comment]
@joelmartinez we'll likely need to bump this up, as it affects the correctness of signatures.

**Comment by joelmartinez** [comment]
@dend ok, I'll cue this up for the next release

**Comment by joelmartinez** [comment]
Implementation notes:

- These signatures are generated in the [`CSharpFullMemberFormatter`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/Updater/Formatters/CSharpFullMemberFormatter.cs) class.
- You'll probably have to work in the `GetMethodDeclaration` class (which currently defers most of the work to the [base class' implementation](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/Updater/Formatters/MemberFormatter.cs#L374). 
- If you inspect that base method, you'll notice that it calls [`AppendModifiers`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/Updater/Formatters/MemberFormatter.cs#L420) after the call to `AppendVisibility` ... override this in the csharp formatter, and provide a custom implementation there that looks at the method definition, and adds `ref`/`readonly` as necessary.

**Comment by joelmartinez** [comment]
This fix will be available in the next release. Thanks for reporting the issue @svick, and thanks for the contribution @TianqiZhang!
