### ISSUE TITLE
When doing updates with mdoc, removed namespace files are not removed when namespace is removed

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#252]
See [internal work item](https://mseng.visualstudio.com/CSI/_workitems/edit/1250678?src=WorkItemMention&src-action=artifact_link).

Essentially, when `mdoc` runs and updates the content, it will remove the namespace folders (for removed namespaces) but will leave behind the `ns-` files.

**Comment by joelmartinez** [comment]
Actually, in my experience, it's not even removing those empty namespace folders (it will clear out the files though, which I think from git's perspective means the folder disappears)
