### ISSUE TITLE
mdoc does not remove language signatures when executed with less languages than original docs

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#271]
When running `mdoc`, a user might choose to generate API signatures for various languages. However, if after generation the user wants to remove signatures en-masse, there is no way to do that. Using less `-lang` params does not, in fact, remove the signatures that are outside the constraints of the lang specification for the run.

**Comment by joelmartinez** [comment]
This issue will be partially resolved in [mdoc 5.7.4.10](https://github.com/mono/api-doc-tools/releases/tag/mdoc-5.7.4.10) ... all members will no longer have this issue, though it will persist for type signatures.

**Comment by joelmartinez** [comment]
mdoc 5.7.4.10 has now been released
