### ISSUE TITLE
Attribute information only made available for C#

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#274]
Compare:

https://docs.microsoft.com/en-us/dotnet/api/system.serializableattribute?view=netframework-4.7.2

https://msdn.microsoft.com/en-us/library/system.serializableattribute(v=vs.110).aspx

Notice that on docs.microsoft.com, we do not render any attribute information for VB, F# or C++, due to the fact that we only have attribute information for C#.

This request covers the need to provide attribute syntax information for other languages.

**Comment by joelmartinez** [comment]
This is actually a function of the front-end (not sure if the conversion happens at Ecma2Yaml stage, or in the docfx templates). I'll illustrate by way of example:

- [`Xamarin.Forms.Internals.IFontElement.FontSize`](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.internals.ifontelement.fontsize?view=xamarin-forms#Xamarin_Forms_Internals_IFontElement_FontSize) ... you can see that it shows the attribute for C#
    ![image](https://user-images.githubusercontent.com/90380/41721916-28d9f320-7535-11e8-8004-de810f695bed.png)  
    But not for F#  
    ![image](https://user-images.githubusercontent.com/90380/41721954-3cd01760-7535-11e8-8092-4d826d7aac08.png)
- Looking at [the EcmaXml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/2c80bed69c511eea58798cae624818812baa4199/docs/Xamarin.Forms.Internals/IFontElement.xml#L59), both the C# and F# signatures **do not** have attributes hard coded into the signature string.
    - C# - `public double FontSize { get; }`
    - F# - `member this.FontSize : double`

So the display of attributes happens on the front-end by iterating over the values in `Attributes/Attribute/AtributeName` ... and it looks like they're only doing it for C# signatures. 

I'm going to close the issue, but let me know if perhaps I've misunderstood the situation :)

**Comment by joelmartinez** [comment]
@dend makes a great point:

-----

I still think there is a mdoc component to it 😊
 
The frontend displays the signatures, yes, however the signature is only available in C# format – its syntax varies across languages. As an example:
 
https://msdn.microsoft.com/en-us/library/system.serializableattribute(v=vs.110).aspx
 
C#:
 
[AttributeUsageAttribute(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Delegate,
        Inherited = false)]
[ComVisibleAttribute(true)]
public sealed class SerializableAttribute : Attribute
 
VB:
 
<AttributeUsageAttribute(AttributeTargets.Class Or AttributeTargets.Struct Or AttributeTargets.Enum Or AttributeTargets.Delegate,
        Inherited := False)>
<ComVisibleAttribute(True)>
 
Notice the syntactical differences – I don’t think it’s something that we should calculate on the frontend, and instead use built-in mdoc formatters to get it.

----

Re-opening this

**Comment by dend** [comment]
@joelmartinez can we allocate this issue into the next sprint? Would be great for us to resolve the customer ask.

**Comment by joelmartinez** [comment]
@dend done :)

**Comment by joelmartinez** [comment]
Ok ... so I'm going to start working on implementing this, but we have to decide on an implementation/spec. For reference, this is what the attributes section currently looks like in [the source XML](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/1c3f8d9cc2ff5ca2b567a8bf5f445e6e8a30b664/docs/Xamarin.Forms/ToolbarItem.xml#L103-L107): 

```xml
      <Attributes>
        <Attribute>
          <AttributeName>System.Obsolete("Activated is obsolete as of version 1.3.0. Please use Clicked instead.")</AttributeName>
        </Attribute>
      </Attributes>
```

There is a collection of `Attributes`, with an `Attribute` tag, and the value being contained in `AttributeName` ... this value, _currently_, is the C# formatted signature.

### Proposal 1

We could simply **add additional `Attribute`s**, along with a new `Language` xml attribute. For example

```xml
      <Attributes>
        <Attribute Language="C#">
          <AttributeName>System.Obsolete("Activated is obsolete as of version 1.3.0. Please use Clicked instead.")</AttributeName>
        </Attribute>
        <Attribute Language="F#">
          <AttributeName>System.Obsolete("Activated is obsolete as of version 1.3.0. Please use Clicked instead.")</AttributeName>
        </Attribute>
      </Attributes>
```

A few notes/thoughts about this:

- Any downstream clients that are not aware of the `Language` xml attribute, will simply display the attributes as-is, all as C# attributes ... this will likely happen until front-end/ecma2yaml work occurs and is deployed ... and will likely cause confusion.
- In this case, both attributes look exactly the same. As it stands, the language-specific delimiters (ie. `[` for C#, and `[<` for F# ... and the separator between multiple `,` and `;` respectively) are handled by the front-end ... **Is this ok, or do we need to have some sort of meta lookup for these language-specific markers in the EcmaXml**?

### Proposal 2

To provide some level of backwards compatibility, we can just let `Attribute` implicitly mean the C# attribute, and then use a language specific tag for the other languages. 

```xml
      <Attributes>
        <Attribute>
          <AttributeName>System.Obsolete("Activated is obsolete as of version 1.3.0. Please use Clicked instead.")</AttributeName>
        </Attribute>
        <FSharpAttribute>
          <AttributeName>System.Obsolete("Activated is obsolete as of version 1.3.0. Please use Clicked instead.")</AttributeName>
        </FSharpAttribute>
      </Attributes>
```

This would mean that downstream clients would probably just ignore those new tags until specific support is added.

### Proposal 3

This third proposal tackles a separate issue; **should we break out the attribute parameter values into more structured metadata**? The driving impetus for this is https://github.com/MicrosoftDocs/feedback/issues/719

So if we wanted to extract and use that obsolete text, we would have to *parse* it from the `AttributeName`, unless we do something like (*note: this 3rd proposal would work with either of the first two proposals that we decide on*):


```xml
      <Attributes>
        <Attribute>
          <AttributeName>System.Obsolete("Activated is obsolete as of version 1.3.0. Please use Clicked instead.")</AttributeName>
          <ParameterValue>"Activated is obsolete as of version 1.3.0. Please use Clicked instead."</ParameterValue>
        </Attribute>
        <FSharpAttribute>
          <AttributeName>System.Obsolete("Activated is obsolete as of version 1.3.0. Please use Clicked instead.")</AttributeName>
          <ParameterValue>"Activated is obsolete as of version 1.3.0. Please use Clicked instead."</ParameterValue>
        </FSharpAttribute>
      </Attributes>
```

We would simply add the value into separate `ParameterValue` entries, which would make it easier to pull out for purposes like that referenced issue.

----

So ... thoughts?

**Comment by svick** [comment]
With Proposal 3, how would you represent named arguments?

E.g. [the `Attribute` class](https://docs.microsoft.com/en-us/dotnet/api/system.attribute?view=netcore-2.1) has the following attribute:

```c#
[System.AttributeUsage(System.AttributeTargets.All, AllowMultiple=false, Inherited=true)]
```

For `AllowMultiple=false`, would you just have `<ParameterValue>AllowMultiple=false</ParameterValue>` (which still requires some parsing), or something more structured?

**Comment by mattleibow** [comment]
Also, the `<AttributeName>` is technically not very useful as it includes everything. For example, it may be better to split this up into more detail, and then things could be more flexible.

For example, the simple attributes can be:

```csharp
[SomethingSpecial]
[EvenBetter("Some Value")]
[PropertiesYay(Name = "Big", Value = 123)]
[Everything(123, "Hello", Optional = true)]
```

```xml
<Attributes>
  <Attribute>
    <AttributeType>My.Namespace.SomethingSpecial</AttributeType>
  </Attribute>
  <Attribute>
    <AttributeType>My.Namespace.EvenBetter</AttributeType>
    <Parameters>
      <ParameterValue Type="System.String">Some Value</ParameterValue>
    </Parameters>
  </Attribute>
  <Attribute>
    <AttributeType>My.Namespace.PropertiesYay</AttributeType>
    <Parameters>
      <ParameterValue Name="Name" Type="System.String">Big</ParameterValue>
      <ParameterValue Name="Value" Type="System.Int32">123</ParameterValue>
    </Parameters>
  </Attribute>
  <Attribute>
    <AttributeType>My.Namespace.PropertiesYay</AttributeType>
    <Parameters>
      <ParameterValue Type="System.Int32">123</ParameterValue>
      <ParameterValue Type="System.String">Hello</ParameterValue>
      <ParameterValue Name="Optional" Type="System.Boolean">true</ParameterValue>
    </Parameters>
  </Attribute>
</Attributes>
```

This is obviously not perfect for different languages or backwards compatibility, but is just way more useful and can be used to construct the attributes for the languages.

**Comment by mattleibow** [comment]
I see comments have appeared and everyone is talking more structure... 😸

**Comment by joelmartinez** [comment]
@svick yes, good point ... it would probably/definitely be better implemented similar to what @mattleibow has proposed in this case.

**Comment by joelmartinez** [comment]
Some implementation notes:

- [`MakeAttributes`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L3360) - this is the method responsible for creating `Attributes/Attribute/AttributesName` elements, and also for separating them out into `FrameworkAlternate` when necessary.
- [`GetCustomAttributes`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L2657) - is responsible for getting the list of attributes, and formatting them into a string.
- [`MakeAttributesValueString`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L3469) - formats the **value** passed into the attribute parameter, into a string.

This work will need to take the logic in `GetCustomAttributes`, and move it into a `CSharpAttributeFormatter`. Additional attribute formatters will need to be added:

- `FSharpAttributeFormatter`
- `VBAttributeFormatter`
- `CppAttributeFormatter`

These will be added to a list based on the `-lang` attributes passed in.

**Comment by joelmartinez** [comment]
So everyone commented on (essentially) **Proposal 3**, and voted (fairly unanimously) to break out the details of the attribute into strongly structured data. However, no one really commented on their preference between Proposals 1 and 2 (probably my fault for structuring the options in this way) :) 

In the absence of further commentary, I will tentatively decide to go with a modified **Proposal 1**, where the different language syntaxes will be separated by a `Language=` attribute. This keeps it in line with how we do `MemberSignature` and `TypeSignature`. The modification to the proposal here, is that I'll just apply that to the `AttributeName` element. With that, and the other proposals made, here's how it might look:

```xml
<Attributes>
  <Attribute>
    <AttributeName Language="C#">SomethingSpecial</AttributeName>
    <AttributeName Language="F#">SomethingSpecial</AttributeName>
    <AttributeType>My.Namespace.SomethingSpecial</AttributeType>
  </Attribute>
  <Attribute>
    <AttributeName Language="C#">EvenBetter("Some Value")</AttributeName>
    <AttributeName Language="F#">EvenBetter("Some Value")</AttributeName>
    <AttributeType>My.Namespace.EvenBetter</AttributeType>
    <Parameters>
      <ParameterValue Type="System.String">Some Value</ParameterValue>
    </Parameters>
  </Attribute>
  <Attribute>
    <AttributeName Language="C#">PropertiesYay(Name = "Big", Value = 123)</AttributeName>
    <AttributeName Language="F#">PropertiesYay(Name = "Big", Value = 123)</AttributeName>
    <AttributeType>My.Namespace.PropertiesYay</AttributeType>
    <Parameters>
      <ParameterValue Name="Name" Type="System.String">Big</ParameterValue>
      <ParameterValue Name="Value" Type="System.Int32">123</ParameterValue>
    </Parameters>
  </Attribute>
  <Attribute>
    <AttributeName Language="C#">Everything(123, "Hello", Optional = true)</AttributeName>
    <AttributeName Language="F#">Everything(123, "Hello", Optional = true)</AttributeName>
    <AttributeType>My.Namespace.Everything</AttributeType>
    <Parameters>
      <ParameterValue Type="System.Int32">123</ParameterValue>
      <ParameterValue Type="System.String">Hello</ParameterValue>
      <ParameterValue Name="Optional" Type="System.Boolean">true</ParameterValue>
    </Parameters>
  </Attribute>
</Attributes>
```

A few notes:

- Since we'll now have `AttributeType`, we can drop the namespace from `AttributeName`, along with the `Attribute` suffix ... this will make the rendered attributes look much nicer.
- In these examples (taken from @mattleibow's proposal), the C# and F# equivalent syntaxes look exactly the same. I'm not going to try to make a distinction and add logic that if they're the same to limit "duplicates". By always listing them when more than one `-lang` is present, it makes all the logic (both here and on the front-end) easier.
- The parameter _values_ will not be further broken down. They will be the same string that is formatted and added into the `AttributeName`. In most cases this will be very straightforward, but in cases of flag enums (for example), it will result in the `ParameterValue` element value being something like `Enum.Val1 | Enum.Val2`
- `FrameworkAlternate` attributes will still be assigned to the `Attribute` element, so that logic doesn't have to change.

@dend because we will be adding multiple `AttributeName` elements (just with different `Language` attributes), we will have to coordinate the release of this with corresponding Ecma2Yaml and front-end template changes, because otherwise, it will likely result in potentially duplicated attributes being displayed on the front-end

**Comment by mimisasouvanh** [comment]
Internal item: https://dev.azure.com/ceapex/Engineering/_workitems/edit/26246
