### ISSUE TITLE
[mdoc] Reflected enums don't get their numeric value in the XML

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#28]
Currently, ECMAXML does not contain the number values for enums. As an example, let’s say we have [RadioButtonState](https://msdn.microsoft.com/en-us/library/system.windows.forms.visualstyles.radiobuttonstate(v=vs.110).aspx).

In the XML, we just get the member names:

```
<Type Name="RadioButtonState" FullName="System.Windows.Forms.VisualStyles.RadioButtonState">
  <TypeSignature Language="C#" Value="public enum RadioButtonState" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi sealed RadioButtonState extends System.Enum" />
  <AssemblyInfo>
    <AssemblyName>System.Windows.Forms</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Enum</BaseTypeName>
  </Base>
  <Docs>
    <summary>To be added.</summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <Member MemberName="CheckedDisabled">
      <MemberSignature Language="C#" Value="CheckedDisabled" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Windows.Forms.VisualStyles.RadioButtonState CheckedDisabled = int32(8)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Windows.Forms.VisualStyles.RadioButtonState</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>To be added.</summary>
      </Docs>
    </Member>
    <Member MemberName="CheckedHot">
      <MemberSignature Language="C#" Value="CheckedHot" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Windows.Forms.VisualStyles.RadioButtonState CheckedHot = int32(6)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Windows.Forms.VisualStyles.RadioButtonState</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>To be added.</summary>
      </Docs>
    </Member>
    <Member MemberName="CheckedNormal">
      <MemberSignature Language="C#" Value="CheckedNormal" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Windows.Forms.VisualStyles.RadioButtonState CheckedNormal = int32(5)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Windows.Forms.VisualStyles.RadioButtonState</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>To be added.</summary>
      </Docs>
    </Member>
    <Member MemberName="CheckedPressed">
      <MemberSignature Language="C#" Value="CheckedPressed" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Windows.Forms.VisualStyles.RadioButtonState CheckedPressed = int32(7)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Windows.Forms.VisualStyles.RadioButtonState</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>To be added.</summary>
      </Docs>
    </Member>
    <Member MemberName="UncheckedDisabled">
      <MemberSignature Language="C#" Value="UncheckedDisabled" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Windows.Forms.VisualStyles.RadioButtonState UncheckedDisabled = int32(4)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Windows.Forms.VisualStyles.RadioButtonState</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>To be added.</summary>
      </Docs>
    </Member>
    <Member MemberName="UncheckedHot">
      <MemberSignature Language="C#" Value="UncheckedHot" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Windows.Forms.VisualStyles.RadioButtonState UncheckedHot = int32(2)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Windows.Forms.VisualStyles.RadioButtonState</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>To be added.</summary>
      </Docs>
    </Member>
    <Member MemberName="UncheckedNormal">
      <MemberSignature Language="C#" Value="UncheckedNormal" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Windows.Forms.VisualStyles.RadioButtonState UncheckedNormal = int32(1)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Windows.Forms.VisualStyles.RadioButtonState</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>To be added.</summary>
      </Docs>
    </Member>
    <Member MemberName="UncheckedPressed">
      <MemberSignature Language="C#" Value="UncheckedPressed" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Windows.Forms.VisualStyles.RadioButtonState UncheckedPressed = int32(3)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Windows.Forms.VisualStyles.RadioButtonState</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>To be added.</summary>
      </Docs>
    </Member>
  </Members>
</Type>
```

If we look at the [reference source](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/VisualStyles/VisualStyleStates.cs,04fc8ac88db0598a), you will notice that there are individual values assigned to each enum entry:

```
[
        SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue")
    ]
    public enum RadioButtonState {
        /// <include file='doc\VisualStyleStates.uex' path='docs/doc[@for="RadioButtonState.UncheckedNormal"]/*' />
        UncheckedNormal = 1, 
        /// <include file='doc\VisualStyleStates.uex' path='docs/doc[@for="RadioButtonState.UncheckedHot"]/*' />
        UncheckedHot = 2, 
        /// <include file='doc\VisualStyleStates.uex' path='docs/doc[@for="RadioButtonState.UncheckedPressed"]/*' />
        UncheckedPressed = 3, 
        /// <include file='doc\VisualStyleStates.uex' path='docs/doc[@for="RadioButtonState.UncheckedDisabled"]/*' />
        UncheckedDisabled = 4, 
        /// <include file='doc\VisualStyleStates.uex' path='docs/doc[@for="RadioButtonState.CheckedNormal"]/*' />
        CheckedNormal = 5, 
        /// <include file='doc\VisualStyleStates.uex' path='docs/doc[@for="RadioButtonState.CheckedHot"]/*' />
        CheckedHot = 6, 
        /// <include file='doc\VisualStyleStates.uex' path='docs/doc[@for="RadioButtonState.CheckedPressed"]/*' />
        CheckedPressed = 7, 
        /// <include file='doc\VisualStyleStates.uex' path='docs/doc[@for="RadioButtonState.CheckedDisabled"]/*' />
        CheckedDisabled = 8
    } 
```

**Comment by jonpryor** [comment]
There's three possible responses for this :-)

1. Do you need the member value? MSDN doesn't show enum values, e.g. [`StringSplitOptions`](https://msdn.microsoft.com/en-us/library/system.stringsplitoptions(v=vs.110).aspx)

2. The values *are* in the XML, embedded within the IL declaration

        .field public static literal valuetype System.Windows.Forms.VisualStyles.RadioButtonState UncheckedPressed = int32(3)

    Of course, nobody wants to *parse* that...

3.  The [ECMA documentation](https://www.ecma-international.org/publications/standards/Ecma-335.htm), which the mdoc format is based on, doesn't provide the literal value either. For example, the documentation for `System.AttributeTargets` contains:

		<Member MemberName="All">
			<MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.AttributeTargets All = Assembly | 0x2 | Class | Struct | Enum | Constructor | Method | Property | Field | Event | Interface | Parameter | Delegate | ReturnValue | GenericParameter" />
			<MemberSignature Language="C#" Value="All = Assembly | 0x2 | Class | Struct | Enum | Constructor | Method | Property | Field | Event | Interface | Parameter | Delegate | ReturnValue | GenericParameter;" />
			<MemberType>Field</MemberType>
			<ReturnValue>
				<ReturnType>System.AttributeTargets</ReturnType>
			</ReturnValue>
			<Parameters />
			<MemberValue>All</MemberValue>
			<Docs>
				<summary>
					<para> Attribute can be applied to any element.</para>
				</summary>
			</Docs>
			<Excluded>0</Excluded>
		</Member>

    I suppose the `<MemberValue/>` element could contain the literal value, but it doesn't, and I'm likewise not sure what could possibly *break* if it contained e.g. `All (32767)` or `All (0x7fff)`.

If we *really* need this, we could instead introduce a `<MemberLiteral/>` element, but that would logically also apply to *any* literal member, e.g. `const string Foo = "Bar"`, so how should strings be encoded -- with or without strings (`<MemberLiteral>Bar</MemberLiteral>` vs. `<MemberLiteral>"Bar"</MemberLiteral>`).

Worse, enum values can change between assembly versions -- or framework versions! -- so this would plausibly need to be stored in some version+framework-specific manner.

**Comment by joelmartinez** [comment]
@dend do you consider this a must-have for [mdoc v5.0](https://github.com/mono/api-doc-tools/milestone/1) ?

**Comment by dend** [comment]
@joelmartinez absolutely not. This is something to consider. I am going over @jonpryor's response to see what would be a good way to add this to the XML.

**Comment by dend** [comment]
@jonpryor the particular information for literal values is interesting to those that try to do [bitwise operations with enums](http://www.alanzucconi.com/2015/07/26/enum-flags-and-bitwise-operators/). Can `<MemberLiteral/>` be an optional element?

**Comment by jonpryor** [comment]
If we have a `<MemberLiteral/>`, it would make sense to have it for all literal (constant, `const`) members, in which case it would need to be optional, because not all members are literal. :-D

Rephrased: it seems silly to me to restrict this to just `enum` types. The same rationale for wanting to know the value of members applies to *all* members. Additionally, JavaDoc does show their values, [at least on Android](https://developer.android.com/reference/android/content/Context.html#ACCESSIBILITY_SERVICE):

> Constant Value: "accessibility"

**Comment by dend** [comment]
Bringing this to the top @joelmartinez - this is another item that we would need to make sure that we maintain parity with MSDN documentation and have no content loss. 

Given @jonpryor's suggestion above, is this something we can close on in terms of schema and implementation?

**Comment by mairaw** [comment]
Not sure if I follow the comment about parity since MSDN never showed the integer values for enums. But @tdykstra was asking me about this the other day.

**Comment by mpMelnikov** [comment]
So, do we decide to add <MemberLiteral> tag for const members and enums?

**Comment by joelmartinez** [comment]
I'll let @dend speak to the issue of needing this in [milestone#3](https://github.com/mono/api-doc-tools/milestone/3) ... but on a technical level, yes I think the proposals here work. A few implementation notes:

- Add support for the element (and validation test) in [the .xsd](https://github.com/mono/api-doc-tools/blob/master/mdoc/Resources/monodoc-ecma.xsd).
- Update the [`UpdateMember`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L1939) method to pull the value from the member definition and create/update the `MemberLiteral` node.
- Update the [`OrderMemberNodes`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L2101) method to include the new `MemberLiteral` node and sort it below the `MemberValue` node.

**Comment by dend** [comment]
@joelmartinez @mpMelnikov yes, let's include this in M3.

**Comment by mpMelnikov** [comment]
@joelmartinez 
UpdateMember method calls GetFieldConstValue method, and there are some "if"s, which disable adding `MemberValue` code for enums and generic types:
```
            if (type != null && type.IsEnum) return false;
            if (type != null && type.IsGenericType ()) return false;
```
So, constants in generic types and enum members don't have `MemberValue` element at all. Also, the method works in such a way, that it doesn't add `MemberValue` element to these class members:
```
        public const bool TestConstBool = true;
        public const string TestConstString = "123";
```
But it works with these class members:
```
        public const int TestConstInt = 12;//result : <MemberValue>12</MemberValue>
        public const Enum1 TestConstEnum = Enum1.Blue;//result : <MemberValue>2</MemberValue>
```
Well, I don't understand the purpose of this method. Should we stay this method as is and add `GetFieldLiteralValue` method, which works as it's described in this ticket? If so, it will break all our integration tests, and we will have to generate all expected xmls again, right?

**Comment by joelmartinez** [comment]
Hmm, you bring up a good point ... it _does_ look like we are using `MemberValue` for const values already. Despite the usage from the original ecma (as described in [jon's comment](https://github.com/mono/api-doc-tools/issues/28#issuecomment-282325914)), which for an enum field simply duplicated the `MemberName`, I think we should modify the `GetFieldConstValue` method to add `MemberValue` for enums. Putting the numeric value of the enum in there is more useful than the string label IMO.

Also, If we move forward in this manner, we won't have to modify the XSD or anything else, since the `MemberValue` already exists.

@mpMelnikov yes, as you correctly guessed this will "break" the integration tests, but only by virtue of the fact that the XMLs will simply need to be updated to reflect these new values.
