### ISSUE TITLE
VB.NET signatures not generated in some cases

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#282]
See [GitHub issue](https://github.com/aspnet/EntityFramework.ApiDocs/issues/23). In certain scenarios, VB.NET signatures are not generated.

See [example file](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions.xml). The parent class has the correct signatures, and the child entities do not.

**Comment by mairaw** [comment]
Should we close this as a dupe of #356? I know this one is older but that one has more issues attached to it.

**Comment by mimisasouvanh** [comment]
Closing as dup of #356.
