### ISSUE TITLE
Update to latest nunit 

### ISSUE THREAD

**Issue by joelmartinez** [mono/api-doc-tools#284]
per https://github.com/mono/api-doc-tools/pull/246 ... which tried to make a number of changes at the same time, and resulted in some tests not passing. Let's update nunit, so that it's not a problem when we subsequently make the other project/nuget changes

**Comment by joelmartinez** [comment]
Whoa, this is great @ChrisMaddock ... thanks for the heads up on this!

**Comment by ChrisMaddock** [comment]
No worries! I had a quick look at #246 and saw some of the problems you hit previously - looks like you'll need to be aware of the path changes described below:

https://github.com/nunit/docs/wiki/Breaking-Changes

I did also pull the repo to have a quick bash, but wasn't able to get a clean build - should the solution build straight out of the box in VS on Windows? Anyway...I'm all out of lunch break now! 😄

Let us know if you hit any other stumbling blocks. 🙂

**Comment by joelmartinez** [comment]
@ChrisMaddock I know this was a bit ago, but I'm going to start working on this in the next release. You mentioned you had issues building on VSWin, was it by chance similar to the issue(s) described here?  
https://github.com/mono/api-doc-tools/issues/308

**Comment by ChrisMaddock** [comment]
@joelmartinez - it was a while ago now, but yes - I had problems with the same packages. I think I also did a work around, then hit further problems, and at that point ran out of lunch break!
