### ISSUE TITLE
AsyncStateMachine attribute on method seems irrelevant

### ISSUE THREAD

**Issue by davidbritch** [mono/api-doc-tools#286]
If you take a look at the `EvaluateJavaScriptAsync` method in the link below, it's decorated with an `AsyncStateMachine` attribute. This is an irrelevance to me, as a consumer of Xamarin.Forms APIs, and also looks ugly. Can it be filtered out?

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.webview.evaluatejavascriptasync?view=xamarin-forms#Xamarin_Forms_WebView_EvaluateJavaScriptAsync_System_String_

**Comment by joelmartinez** [comment]
@terrajobst @dend ... thoughts on filtering this particular attribute out (`AsyncStateMachineAttribute`)? Seems like it's low value to include in the documentation if it's [added by the compiler](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.asyncstatemachineattribute?view=netframework-4.7.2#remarks):

> **You shouldn't apply the `AsyncStateMachine` attribute to methods in your code**. For methods that have the async modifier, **the compiler will apply** the `AsyncStateMachine` attribute in the IL that the compiler emits.
