### ISSUE TITLE
internal APIs are being added to the reflection

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#289]
If you compare Docs vs MSDN for the InstanceContext class, you'll see that the number of APIs shown on Docs is bigger. It seems that internal APIs are being added to the reflection when they probably shouldn't? There also might be some rules because the class is sealed? Maybe @rpetrusha can help to figure out the appropriate rules of what should be excluded by default.

Compare
https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.instancecontext
with 
https://msdn.microsoft.com/en-us/library/system.servicemodel.instancecontext

/cc @dend

**Comment by dend** [comment]
In the meantime, we can apply the `_filter.xml` to exclude things that should not be published.

**Comment by mairaw** [comment]
Sure @dend, but finding those would be painful. This is just an example I found while looking at the undoc api report.

**Comment by mairaw** [comment]
I talked to @rpetrusha and he had filed an issue on this a long time ago. I also found issue #89 that is the same as this one. 

There's also another issue that I discovered with this investigation. The sealed keyword is not being shown on Docs, so I'll open a separate issue for this.

**Comment by mairaw** [comment]
Duplicate of #89
