### ISSUE TITLE
Wrong index for FrameworkAlternate?

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#291]
The indexes for this API seems to be a little bit off:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO.Compression/DeflateStream.xml#L387

Not sure if there are other occurrences like this. I've noticed this while exporting missing content.

The index should match for the params with the same type. But instead they're mixed and matched with others somehow.
![image](https://user-images.githubusercontent.com/12971179/42852866-d5654588-89e7-11e8-9c95-d359153d3d50.png)

/cc @dend @joelmartinez

**Comment by joelmartinez** [comment]
Hi @mairaw ... yes, good eye :) This issue was already reported here:  
https://github.com/mono/api-doc-tools/issues/266 

It's on the roadmap to be resolved soon. Will close this issue as a dupe since #266 exists. Thanks!

**Comment by joelmartinez** [comment]
This issue is unfortunately [still present](https://github.com/dotnet/dotnet-api-docs/blob/0012e5ded56afa6e8fd1f359bc62098b949c91b0/xml/System.IO.Compression/DeflateStream.xml#L397) with the latest build.

Additionally, there seems to be a related issue with indexing, where [generic parameters with no names are involved](https://github.com/dotnet/dotnet-api-docs/pull/463/files/49f51e85e33a589b8aead775f1ac0c47ba2dd27c#diff-e33326a1b0cb22ac3b75a99953a5f2ceL30)

**Comment by mairaw** [comment]
Another repro:
M:System.Security.Cryptography.SHA256Managed.HashCore(System.Byte[],System.Byte[],System.Int32,System.Int32)
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/SHA256Managed.xml#L206

Actual:
  <Parameters>
        <Parameter Name="array" Type="System.Byte[]" Index="0" FrameworkAlternate="netcore-2.0;netcore-2.1;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netstandard-2.0;xamarinandroid-7.1" />
        <Parameter Name="data" Type="System.Byte[]" Index="0" FrameworkAlternate="xamarinios-10.8" />
        <Parameter Name="rgb" Type="System.Byte[]" Index="1" FrameworkAlternate="netcore-2.0;netcore-2.1;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netstandard-2.0;xamarinandroid-7.1" />
        <Parameter Name="start" Type="System.Int32" Index="1" FrameworkAlternate="xamarinios-10.8" />
        <Parameter Name="ibStart" Type="System.Int32" Index="2" FrameworkAlternate="netcore-2.0;netcore-2.1;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netstandard-2.0;xamarinandroid-7.1" />
        <Parameter Name="length" Type="System.Int32" Index="2" FrameworkAlternate="xamarinios-10.8" />
        <Parameter Name="cbSize" Type="System.Int32" Index="3" />
      </Parameters>

Expected for 4.8:
index 0 should be rgb, 1 ibstart and 2 cbSize:
![image](https://user-images.githubusercontent.com/12971179/49353937-3c6a3500-f675-11e8-8485-fa09c123a1ed.png)

**Comment by joelmartinez** [comment]
Thanks for following up with more information @mairaw … this issue will soon be front and center, as I'm currently working on another issue. But as soon as this current issue is resolved, I'll be addressing this one.

**Comment by joelmartinez** [comment]
Resolved in mdoc 5.7.4.6
