### ISSUE TITLE
API remarks come first in API docs :(

### ISSUE THREAD

**Issue by davidbritch** [mono/api-doc-tools#297]
To me, the primary purpose of API docs is to list the API (constructors, fields, properties etc.). That's why I look at API docs.

The second purpose, to me, is to provide examples of using the API. In case I'm stuck and can't figure out the API (ignoring that conceptual docs do this).

Take a look at the Xamarin.Forms [`Button`](https://docs.microsoft.com/en-gb/dotnet/api/xamarin.forms.button?view=xamarin-forms) type. It first lists remarks, then the API. Can this be changed so the API comes first, followed by remarks?

Obviously this is a completely subjective view so feel free to tell me no and close the issue :)

**Comment by joelmartinez** [comment]
Oh I see, by "the API", you mean the list of types. I can definitely understand where you're coming from, but based on all the user research we've done so far, most users' primary expectations is actually backwards from what you've stated here. They tell us that they expect first to see examples and information about how to use a type (ie. how it is now).

Additionally, there is the lefthand navigation menu that you can use to browse the members of a type:  
![image](https://user-images.githubusercontent.com/90380/43440990-45c17156-9467-11e8-8bd1-98ab8ea42191.png)

I'll close this out for now :)
