### ISSUE TITLE
mdoc inserts incorrect UTF-16 BOM @ start of file and no trailing at end

### ISSUE THREAD

**Issue by lobrien** [mono/api-doc-tools#299]
When mdoc update is run, the number of "modified" XML docs is huge. This is due in part to mdoc writing a byte-order-mark for UTF-16 U+FEFF (UTF-16 Big Endian!) at the beginning of the file and clipping the final line return from the file. 

I'm pretty sure the EcmaDoc XML files should be treated as UTF-8 text files. 

```
$ file *.xml
DraggingEventArgs.xml:                                                 UTF-8 Unicode (with BOM) text
INSLayoutManagerDelegate.xml:                                          UTF-8 Unicode (with BOM) text, with very long lines
INSTextAttachmentContainer.xml:                                        UTF-8 Unicode (with BOM) text, with very long lines
INSTextLayoutOrientationProvider.xml:                                  UTF-8 Unicode (with BOM) text, with very long lines
INSTextStorageDelegate.xml:                                            UTF-8 Unicode (with BOM) text, with very long lines
IUIAccelerometerDelegate.xml:                                          UTF-8 Unicode (with BOM) text
IUIAccessibilityContainer.xml:                                         UTF-8 Unicode (with BOM) text, with very long lines
```

**Comment by joelmartinez** [comment]
This is the code snippet that writes the XML files:  
https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L542-L551

```csharp
        private static void WriteXml (XmlElement element, System.IO.TextWriter output)
        {
            OrderTypeAttributes (element);
            XmlTextWriter writer = new XmlTextWriter (output);
            writer.Formatting = Formatting.Indented;
            writer.Indentation = 2;
            writer.IndentChar = ' ';
            element.WriteTo (writer);
            output.WriteLine ();
        }
```

Note that after the XML is written, there is an additional line of `output.WriteLine ()` to add the trailing line. 

The `TextWriter` that's passed to it is here:
https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L1373-L1381

```csharp
        private static TextWriter OpenWrite (string path, FileMode mode)
        {
            var w = new StreamWriter (
                new FileStream (path, mode),
                new UTF8Encoding (false)
            );
            w.NewLine = "\n";
            return w;
        }
```

note [`new UTF8Encoding(false)`](https://docs.microsoft.com/en-us/dotnet/api/system.text.utf8encoding.-ctor?view=netframework-4.7.2#System_Text_UTF8Encoding__ctor_System_Boolean_), which passes in `true` to "specify that the GetPreamble() method returns a Unicode byte order mark" for UTF8.

Can you recommend different settings for these APIs that would produce the desired result?

**Comment by joelmartinez** [comment]
Just brainstorming, I wonder if this could be some sort of machine-specific configuration issue? Only mentioning because I don't ever see this kind of widescale change on files that have no changes otherwise, when doing `mdoc update` on EcmaXml repositories.

Can you `git config --list` in your api repo? Mine shows:

```bash
$ git config --list
credential.helper=osxkeychain
filter.lfs.clean=git-lfs clean %f
filter.lfs.smudge=git-lfs smudge %f
filter.lfs.required=true
user.name=XXXX
user.email=XXXX
help.autocorrect=10
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
remote.origin.url=git@github.com:xamarin/ios-api-docs
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```

My config doesn't seem to show anything helpful, but maybe you have some different setting?

**Comment by joelmartinez** [comment]
Maybe you'll have something for `i18n.commitEncoding` or `core.checkRoundtripEncoding`?

**Comment by lobrien** [comment]
I'm totally confused, but I think the BOM issue relates to the difference between mdoc using the discouraged-but-not-deprecated `XmlTextWriter` and me using the `XmlWriter`. I don't see anything in my git config that is different (not sure what `precomposeunicode` does, but mine is `true` too).

**Comment by joelmartinez** [comment]
@lobrien there **should** be a way to customize the stream that you're passing to the `XmlWriter`, to effectively use [the same settings](https://github.com/mono/api-doc-tools/issues/299#issuecomment-409105200) as mdoc :) 

Remind me next week, and I'll look at making a workbook to demo it

**Comment by joelmartinez** [comment]
@lobrien try these settings for your `XmlWriter`

```csharp
XmlWriterSettings settings = new XmlWriterSettings
{
    Encoding = new System.Text.UTF8Encoding(false),
    NewLineChars = "\n",
    Indent = true,
    IndentChars = "  "
};

XmlWriter writer = XmlWriter.Create("somefile.xml", settings);
```

I didn't actually run/test this ... but I believe the `IndentChars="  "` (note the **two** space characters in that string) are equivalent to mdoc's `writer.Indentation=2` setting.

Let me know if adding this to your tools fixes the issue that you're seeing.

**Comment by lobrien** [comment]
Beatcha' to it: 

OK, so the way I've been doing it is `SaveA` and the way mdoc is doing it is `SaveB`:

```
[08:41:40]larryobrien@Larrys-iMac:~/Desktop$ file Save*.xml
SaveA.xml: UTF-8 Unicode (with BOM) text, with no line terminators
SaveB.xml: ASCII text
[08:41:44]larryobrien@Larrys-iMac:~/Desktop$ git diff SaveA.xml SaveB.xml


diff --git a/SaveA.xml b/SaveB.xml
index 528044d..b9f55a0 100644
--- a/SaveA.xml
+++ b/SaveB.xml
@@ -1 +1 @@
-<U+FEFF><Foo />
\ No newline at end of file
+<Foo />
```

Which duplicates the behavior pretty well, I think. 

```
---
uti: com.xamarin.workbook
id: 7b2e24ff-d004-4f5c-95f7-53545fdd9427
title: BOM_XML.work
platforms:
- Console
---

using System.IO;
using System.Xml.Linq;

var doc = XDocument.Parse("<Foo/>");

void SaveA(XDocument d) 
{
    var path = "/Users/larryobrien/Desktop/SaveA.xml";
    var settings = new System.Xml.XmlWriterSettings();
    settings.NewLineChars = "\n";
    settings.OmitXmlDeclaration = true;
    settings.Indent = true;
    using(var writer = System.Xml.XmlWriter.Create(path, settings))
    {
        doc.Save(writer);
        writer.Dispose();
    }
}
```

```csharp
using System.Xml;
using System.Text;
using System.IO;

void SaveB(XDocument d)
{
    var path = "/Users/larryobrien/Desktop/SaveB.xml";
    var w = new StreamWriter (
        new FileStream (path, FileMode.Create),
        new UTF8Encoding (false)
    );
    w.NewLine = "\n";
    XmlTextWriter writer = new XmlTextWriter (w);
    writer.Formatting = Formatting.Indented;
    writer.Indentation = 2;
    writer.IndentChar = ' ';
    d.Root.WriteTo (writer);
    w.WriteLine ();
    w.Close();
}

SaveA(doc);
SaveB(doc);
```

**Comment by joelmartinez** [comment]
@lobrien So what happens if you add `Encoding = new System.Text.UTF8Encoding(false)` to your `XmlWriterSettings` ?

**Comment by lobrien** [comment]
I added ^ and changed `OmitXmlDeclaration` to `false` and get:

```
$ git diff SaveA.xml SaveB.xml
diff --git a/SaveA.xml b/SaveB.xml
index bb2128a..b9f55a0 100644
--- a/SaveA.xml
+++ b/SaveB.xml
@@ -1,2 +1 @@
-<?xml version="1.0" encoding="utf-8"?>
-<Foo />
\ No newline at end of file
+<Foo />
[08:54:48]larryobrien@Larrys-iMac:~/Desktop$ file Save*.xml
SaveA.xml: XML 1.0 document text, ASCII text
SaveB.xml: ASCII text
```

**Comment by joelmartinez** [comment]
Alright ... just to close the loop here, this is what we ended up with, that reproduces mdoc's output when using `XDocument` in a script:

```csharp
void SaveC(XDocument d, string path) 
{
    var settings = new System.Xml.XmlWriterSettings();
    settings.NewLineChars = "\n";
    settings.OmitXmlDeclaration = false;
    settings.Indent = true;
    settings.IndentChars = "  ";
    
    using(var stream = new StreamWriter(path, false, new UTF8Encoding(false)))
    using(var writer = System.Xml.XmlWriter.Create(stream, settings))
    {
        doc.Save(writer); 
        writer.Dispose();
        stream.WriteLine();
        stream.Dispose();
    }
}
```
This uses the same indent settings, the new newline char, the same encoding, and emits the trailing line.

**Comment by joelmartinez** [comment]
@lobrien I created a TODO item to document this, and closed this particular GH issue in the meantime:
https://github.com/mono/api-doc-tools/projects/3#card-12106292

**Comment by lobrien** [comment]
Final snippet that: 
No BOM
Trailing carriage return

```
    var settings = new System.Xml.XmlWriterSettings();
    settings.NewLineChars = "\n";
    settings.OmitXmlDeclaration = false;
    settings.Indent = true;
    settings.IndentChars = "  ";
    
    using(var stream = new StreamWriter(path, false, new UTF8Encoding(false)))
    using(var writer = System.Xml.XmlWriter.Create(stream, settings))
    {
        doc.Save(writer); 
        writer.Dispose();
        stream.WriteLine();
        stream.Dispose();
    }
```

Re-canonicalized apple-api-docs in 405560bb
