### ISSUE TITLE
[mdoc] Generate long-form identifiers

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#31]
Today, `mdoc` does not generate long-form identifiers (e.g. `T:System.Data.DataRow`) for namespaces/types/members with the exception of `index.xml` where it references those in `ExtensionMethods`:

```
<ExtensionMethod>
      <Targets>
        <Target Type="T:System.Data.DataRow" />
      </Targets>
      <Member MemberName="SetField&lt;T&gt;">
        <MemberSignature Language="C#" Value="public static void SetField&lt;T&gt; (this System.Data.DataRow row, System.Data.DataColumn column, T value);" />
        <MemberSignature Language="ILAsm" Value=".method public static hidebysig void SetField&lt;T&gt;(class System.Data.DataRow row, class System.Data.DataColumn column, !!T value) cil managed" />
        <MemberType>ExtensionMethod</MemberType>
```

**Comment by jonpryor** [comment]
I'm not quite sure I follow. *Where* do you want `mdoc` to generate Class References? *Everywhere* (`//InterfaceName`, `//Parameters/Parameter/@Type`, `//ReturnValue/ReturnType`, `//BaseTypeName`, etc.)?

I don't understand the desire/need for "everywhere;" all those places can only be types, so prefixing with `T:` would give a proper CREF, and omitting them "saves" two bytes per reference. (Woo?)

More importantly, such a change would be a file format semantic change, requiring that existing readers & writers be updated to emit the new semantics, *or* that e.g. `monodoc.dll` support both formats. ("What existing readers," I hear you ask? We've written several import utilities over the years to import HTML (iOS, Android JavaDoc) into mdoc XML format.)

Additionally, if (when?) we need to generate an updated set of ECMA-335 documentation, the fewer divergences in the file formats, the easier it'll be to emit that documentation. (Yes, there are already some divergences, largely in mode's multi-file approach vs. ECMA's original single-file approach, but *other than that*, the file formats are compatible.)

**Comment by dend** [comment]
For context, the implementation of this ask would be adding the result of a call to `DocCommentId.GetDocCommentId(typeOrMember)` [in Cecil](https://github.com/mono/cecil/blob/master/rocks/Mono.Cecil.Rocks/DocCommentId.cs#L233).

It's highly recommended that we have a way to read Doc IDs because it’s the only format that was standardized across all languages that can uniquely identify the API by name. It’s already supported by virtually all IL analysis tools (CCI1, CCI2, Cecil, Roslyn etc).
 
If we don’t use it, our API doc experience is likely to have bugs we're not even aware of yet in terms of API lookups or maintenance. For instance, how do you represent explicit operators? You need to include the return type because they are overloaded based on return type, which usually doesn’t happen. The Doc ID format takes care of these nuances.
 
We also need to store the DocID anyways, otherwise we’ll have to re-implement tools like F1 in VS to lookup based on other formats.

**Comment by dend** [comment]
To avoid breaking things, can we integrate it as another language, such as:

```
<Type Name="ProjectItemDefinition" FullName="Microsoft.Build.Evaluation.ProjectItemDefinition">
  <TypeSignature Language="C#" Value="public class ProjectItemDefinition" />
  <TypeSignature Language="DocID" Value=CECIL_GENERATED_DOC_ID" />
```

**Comment by joelmartinez** [comment]
I propose that we simply make this an optional flag, something like:

    mdoc update -o path lib.dll -add-docid

_apologies for the issue close, that was a mistake_ :)

**Comment by terrajobst** [comment]
As @dend said, the DocID format is the quasi standard for unique API identifiers and is supported by most tools that matter.

For types, the difference of DocIds to simply names isn't very interesting. The cases where it starts to matter much are those:

* Constructed types (generics, arrays)
* Reference to generic parameters
* Explicit interface implementations
* Explicit operators

Being able to correlate output from different tools is super important.

**Comment by terrajobst** [comment]
> I propose that we simply make this an optional flag

Why not simply add the data to the resulting file in all cases?

**Comment by joelmartinez** [comment]
@terrajobst I mainly proposed it as a compromise, because it's a new element and existing customers that happen to update to v5 would get new/noisy updates in their checkin without any real gain in functionality (as they obviously won't currently be using `DocId` yet).

This way you can opt into it ... and perhaps in a future release we can standardize on it. But an opt-in model lets us defer that particular decision for a future date :)

**Comment by dend** [comment]
@joelmartinez I think it's fine to use it as an opt-in for now, and listen to feedback from customers. The goal here is to make sure that we integrate it properly in the MS docs pipeline, but I understand that other customers have needs different from ours and also use `mdoc`.

**Comment by jonpryor** [comment]
I think it's fine to add it in all cases. It's "noise," but it's easy to ignore noise.

I just wish that the original description had mentioned the `//*Signature/@Value` use. That makes a lot of sense.

**Comment by terrajobst** [comment]
@joelmartinez 

> I mainly proposed it as a compromise, because it's a new element and existing customers that happen to update to v5 would get new/noisy updates in their checkin without any real gain in functionality 

That makes total sense; I can see that.

**Comment by joelmartinez** [comment]
You can now find this feature in [preview v5.0.0.5](https://github.com/mono/api-doc-tools/releases/tag/preview-5.0.0.5) (usage details in those release notes).

A bit of context, I ultimately decided to go with the opt-in model of providing a `-use-docid` flag on the command line. In a future release we can talk about making this a default value if it's really wanted, but it ultimately seemed like a niche use case :)
