### ISSUE TITLE
F#: Item, Ordinal, and Cardinal properties should not be shown

### ISSUE THREAD

**Issue by cartermp** [mono/api-doc-tools#315]
![image](https://user-images.githubusercontent.com/6309070/44372765-54d58b80-a49a-11e8-8263-0094a0b9d99a.png)

These are an implementation detail for indexing into a data structure that you can apply to any appropriate data structure. We implement `Item` for F# lists, but this is not a part of its API.

**Comment by joelmartinez** [comment]
This kind of thing, where we just want to _hide_ something is something that would be a front-end implementation ... since as far as mdoc goes, this is just CLI/Metadata. 

@dend, can these members be filtered out using the filter xml?
