### ISSUE TITLE
[mdoc][xml] Generated XML contains 0x00 that breaks the XDocument parser

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#32]
Available in files such [as this](https://apidrop.visualstudio.com/_git/XMLDevDrop?path=%2Ffeb-24-2017%2FSystem.Windows.Forms%2FMaskedTextBox.xml&version=GBmaster&_a=contents).

Getting the following errors when trying to use `XDocument.Load(string fileName)`:

```
Failed to load E:\apidrop\XMLDevDrop\feb-24-2017\System.Windows.Forms\MaskedTextBox.xml: '.', hexadecimal value 0x00, is an invalid character. Line 1168, position 65.
Failed to load E:\apidrop\XMLDevDrop\feb-24-2017\System.Windows.Forms\TextBox.xml: '.', hexadecimal value 0x00, is an invalid character. Line 417, position 65.
```

Both files are generated out of the `System.Windows.Forms.dll` assembly in .NET Framework.

**Comment by joelmartinez** [comment]
hmm, for the linked file, the line in question is: 

```
          <AttributeName>System.ComponentModel.DefaultValue('&#x0;')</AttributeName>
```

**Comment by jonpryor** [comment]
I'm not entirely sure what should be done here.

Consider the source code for [`MaskedTextBox.PasswordChar`](https://github.com/mono/mono/blob/ef380e3/mcs/class/System.Windows.Forms/System.Windows.Forms/MaskedTextBox.cs#L618):

```csharp
partial class MaskedTextBox {

	[DefaultValue ('\0')]
	public char PasswordChar {...}
}
```

The default value *is* ASCII NUL, so this is the value persisted in the XML:

```xml
<AttributeName>System.ComponentModel.DefaultValue('&#x0;')</AttributeName>
```

I suppose we could "C#-ify" the `<AttributeName/>` values, and instead emit:

```xml
<AttributeName>System.ComponentModel.DefaultValue('\0')</AttributeName>
```

That would at least allow the XML to be loaded by `XDocument`. If we do this, we should probably do the same thing for other C# escape characters, like `\t`, `\n`, `\r`, `\b`, `\v`, etc.

**Comment by TianqiZhang** [comment]
I'm doing exactly the same (translating &#x0; to \0) in order to load current xml...If mdoc can do this it will be great!
