### ISSUE TITLE
Duplicate DocID entries for the same value

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#346]
This happens for a few APIs and I only noticed the problem because every time we run CI, the values jump from one line to the other

e.g. https://github.com/dotnet/dotnet-api-docs/commit/4a29d860cc543990494bd621b64813d4b1490e52#diff-471c4d71af4727f441c4e438a0e4ab14

![image](https://user-images.githubusercontent.com/12971179/44940472-d2738400-ad43-11e8-9631-ce3b9ac61a70.png)

**Comment by mairaw** [comment]
The DOCID element should never have a FrameworkAttribute. A different DocID would mean it's a different member.

**Comment by joelmartinez** [comment]
the fix for this should also resolve the secondary effect of "jumping FXAs" ... which happens when a signature is the same as another, and subsequent mdoc runs will move the FXA values between the two entries back and forth

**Comment by joelmartinez** [comment]
Internal item [logged](https://ceapex.visualstudio.com/Engineering/_workitems/edit/93828)
