### ISSUE TITLE
CI run introduced a new member that existed for other monikers

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#357]
See https://github.com/dotnet/dotnet-api-docs/pull/523#discussion_r219366484 for more context

M:System.Lazy\`1.#ctor(`0) exists in .NET Core, but during CI run this member was added to some of the framework monikers.

**Comment by joelmartinez** [comment]
@mairaw as I mentioned via email ... I've included **a** fix that relates to this in mdoc 5.7.4, however I'm not 100% certain that it will truly resolve the issue, which seems to stem from exported types. When a type is exported, mdoc tries to resolve the assembly that it was exported to. In doing so, it will load the `TypeDefinition` **in that assembly**. So it seems like what's happening is that a type export (for ``Lazy`1`` for example, `System.Core.dll` exports it to either `mscorlib` or `System.Runtime`, so depending on which version of that gets loaded, there might be a discrepancy).

So let's get this run again, and the 5.7.4 release has additional information that might be able to help us decipher what's going on, if it is still occurring.

**Comment by dend** [comment]
@mairaw given that we are now running the latest .NET CI jobs with `mdoc` 5.7.4, can you please verify whether the jumping moniker issue is gone?

**Comment by mairaw** [comment]
I think we still have that issue. Look at the latest CI run which introduced some new members to old monikers that shouldn't be there.
https://github.com/dotnet/dotnet-api-docs/pull/1252

**Comment by joelmartinez** [comment]
@mairaw yes I'm still actively investigating this. It's tricky because it seems to be environment-dependent … more to come.

**Comment by joelmartinez** [comment]
Corresponding internal DevOps item: https://ceapex.visualstudio.com/Engineering/_workitems/edit/52655
