### ISSUE TITLE
Mdoc unexpectedly duplicates copy into Index.xml; Mdoc doesn't return 0 iff no changes are made

### ISSUE THREAD

**Issue by kingces95** [mono/api-doc-tools#38]
Per discussion with @joelmartinez:

Expected mdoc to not duplicate copy. Actually observed instances where mdoc duplicates copy. Duplicate copy is problematic because it's not clear which duplicate should be updated and if the duplicates diverge it's not clear which one is authoritative. 

For example, if I compile an assembly containing a public API, then run `mdoc update` to generate a xml stub `<summary>To be added.</summary>`, then replace the stub with copy like `<summary>This is a public API.</summary>` then I expect running `mdoc update` again will not change any other files. What actually happens is that mdoc will duplicate the copy into `index.xml`. This can be seen happening in this [PR](https://github.com/xamarin/Xamarin.Forms/pull/805). 

I also expect that if `mdoc update` makes non-whitespace updates to any file then it return a non-zero error code otherwise it return zero. What actually happens is undocumented and so other less elegant solutions must be employed to discover if `mdoc` made any changes.

____
Fixing this issue will allow the XF team to achieve it's goal of (1) failing the build unless every public API has corresponding mdoc xml and (2) having our doc writer be able to update copy without having to build. Currently we're able to (inelegantly) achieve the first goal but not the second the due to this issue. 

Here is an elaboration of our doc work flow:

1. Developer makes changes, builds, and runs this [bat file](https://github.com/xamarin/Xamarin.Forms/blob/master/update-docs-windows.bat) to generate mdoc xml stubs for any new public APIs introduced. The changes and the mdoc xml are both included in the PR.

2. The CI system enforces mdoc xml is present for every public API by running the same bat file again after the build. The bat file returns 0 (success) iff a copy made of the mdoc xml before the build + `mdoc update` is the same as the generated mdoc xml. The test for changes is not as simple as just checking the return code of mdoc as its not documented to return zero iff no changes were made. Hence the less elegant method of copy/regenerate/compare is employed by the bat file.

3. The doc writer submits a PR with updates only to the mdoc xml content and submits the PR. The doc writer does not want to have to have to re-run `mdoc update` as that would first require the doc writer to build the product. Requiring the doc writer to build is not ideal as configuring and maintaining a box to successfully build is not always a trivial exercise. Unfortunately, due to this bug, the doc writers PR fails CI because `mdoc update` results duplicates the new copy to `index.xml`.

**Comment by joelmartinez** [comment]
To add a bit more context ... the reason this is happening is that `index.xml` is updated every time `mdoc update` is run, so whenever a doc writer updates the documentation, it causes `index.xml` to fall out of sync until the next time `mdoc update` happens to run. 

I propose that we get rid of index.xml entirely, and simply generate it when `mdoc assemble` is run.
