### ISSUE TITLE
Add FrameworkAlternate attribute for exceptions, thread safety and permissions

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#387]
These three properties today do not carry a `FrameworkAlternate` attribute in the schema:

* Exceptions
* Thread safety
* Permissions

This feature request is about having that attribute present, to make sure that we can properly version the content.

**Comment by mimisasouvanh** [comment]
Internal feature: https://ceapex.visualstudio.com/Engineering/_workitems/edit/129109
