### ISSUE TITLE
The <example> attribute is repeated two or three times in XML files

### ISSUE THREAD

**Issue by divega** [mono/api-doc-tools#391]
Copying from https://github.com/aspnet/EntityFramework.ApiDocs/issues/33, because I suspect the issue is in Mono's documentation toolchain. 
 
We noticed this because we received a PR that was sent to fix the API docs for one of our classes. It turns out that it happens on other classes too, but the source code only contains one copy of the <example> attribute:

This is the PR: https://github.com/aspnet/EntityFramework.ApiDocs/pull/30. The API docs are generated based on the code base in https://github.com/aspnet/EntityFrameworkCore/.

**Comment by joelmartinez** [comment]
Hi @divega … thanks for reporting this issue. Does this duplication occur every time the xml docs get updated?

**Comment by divega** [comment]
@joelmartinez I am not sure because I don't update the docs. Maybe @dendeli-msft knows.

**Comment by joelmartinez** [comment]
I think this might be related to #180 

@divega can you tell me if this issue has resurfaced since this was originally reported?

**Comment by smitpatel** [comment]
@joelmartinez - Yes, we are seeing this issue again. (e.g. [ThenInclude](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.theninclude?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ThenInclude%60%603);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7.2);k(DevLang-csharp)%26rd%3Dtrue&view=efcore-3.0))

We regenerated this API on Oct 7, 2019. The original source code does not contain duplicated examples but xml file generated by tool contains them.
