### ISSUE TITLE
Some classes are missing implicit conversion operators

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#398]
For example:
https://docs.microsoft.com/en-us/dotnet/api/system.printing.indexedproperties.printint32property#operators

Compare with MSDN:
![image](https://user-images.githubusercontent.com/12971179/50037066-c1811280-ffc2-11e8-8e3a-f7efbf6f5294.png)

This is what ILDASM shows:
![image](https://user-images.githubusercontent.com/12971179/50037079-ce9e0180-ffc2-11e8-9758-b70757fed127.png)

But there's only one op_Implicit member in https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Printing.IndexedProperties/PrintInt32Property.xml.

**Comment by mimisasouvanh** [comment]
Internal [bug](https://ceapex.visualstudio.com/Engineering/_workitems/edit/167411) logged.

**Comment by mimisasouvanh** [comment]
@mairaw This was fixed by the PR: https://github.com/mono/api-doc-tools/pull/477.
