### ISSUE TITLE
.NET API Reference: Math.PI syntax displays wrong value

### ISSUE THREAD

**Issue by rpetrusha** [mono/api-doc-tools#412]
The documentation for [Math.PI](https://docs.microsoft.com/en-us/dotnet/api/system.math.pi) shows that Pi is a constant whose value is 3.14159265358979:
 
![image](https://user-images.githubusercontent.com/10886961/52367544-31c77580-2a01-11e9-9c93-d53457c3a2ac.png)

This is incorrect. (It happens to be the value of Pi when displayed with default precision using the "G" format string. If its value is retrieved in this way using reflection, full precision with the "R" or "G17" format string should always be used).  

The actual value defined in source is the same for both .NET Core and .NET Framework:
- .NET Core: `public const double PI = 3.14159265358979323846;`
- .NET Framework: `public const double PI = 3.14159265358979323846;`

Unfortunately, this value exceeds the precision of the Double type, so the value stored in assembly metadata is slightly different: `.field public static literal float64 PI = float64(3.1415926535897931)`. This represents Math.PI formatted with the "R" format string.

**Comment by tannergooding** [comment]
It is worth noting that, for full framework and .NET Core prior to 3.0; the roundtrip format specifier (`"R"`) will not always produce a round-trippable value.
* .NET Core 3.0 was recently updated such that `ToString()`, `ToString("G")`, and `ToString("R")` (for both `double` and `float`) will always produce the shortest round-trippable string.

If you would like to produce a string that is guaranteed to roundtrip; you should use `double.ToString("G17")` and `float.ToString("G9")`.

**Comment by joelmartinez** [comment]
Awesome, much appreciate the feedback! 

Implementation details:

- This change should probably go in the `AttributeValueFormatter` class, here: https://github.com/mono/api-doc-tools/blob/b4d58f0396f18bf594394359d20f94e71cc926d4/mdoc/Mono.Documentation/Updater/Formatters/AttributeValueFormatter.cs#L49

**Comment by anmeng10101** [comment]
link to [internal track](https://ceapex.visualstudio.com/Engineering/_workitems/edit/109280)

**Comment by joelmartinez** [comment]
This issue has been resolved in https://github.com/mono/api-doc-tools/pull/450

It will be available when mdoc 5.7.5 ships
