### ISSUE TITLE
System.IO.DirectoryInfo.FullName keeps getting erased on latest CI runs

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#416]
On the latest CI runs for .NET, the API System.IO.DirectoryInfo.FullName keeps getting removed from the runs. I checked and it does still exist. See the version of that API in .NET Framework - mscorlib.dll:

![image](https://user-images.githubusercontent.com/12971179/52755252-31574d80-2fb2-11e9-8a9e-520cac7398dd.png)

**Comment by joelmartinez** [comment]
Ok ... so I've already tried to reproduce this locally, unsuccessfully; the member is always present in all my local runs. @mairaw can you tell me if you're seeing this on runs from a specific branch of the `binaries` repository (I did it from `master`)?

**Comment by mairaw** [comment]
Ah sorry. I've been running my CI runs from the mdoc-update branch. As soon as all my changes are in, I'll port everything into master. But you'd need to run without the 3.0 assemblies. Right now, I'm trying to figure it out what I'm missing in the dependencies folder since the last CI failed.

**Comment by joelmartinez** [comment]
@mairaw when you get a chance, can you add some references to other examples of this happening? per the meeting, there's some other instances where known members keep getting removed

**Comment by joelmartinez** [comment]
internal item [logged](https://ceapex.visualstudio.com/Engineering/_workitems/edit/78033)

**Comment by mairaw** [comment]
Some other examples can be seen at:
- https://github.com/dotnet/dotnet-api-docs/pull/2200/commits/6c2145debbab043d59e409fe70e5d57436504269
- https://github.com/dotnet/dotnet-api-docs/pull/2197/files
