### ISSUE TITLE
Split <block subset="none" type="note"><para> to different lines

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#421]
In order for us to move our API repo to markdig, we apparently need to split those two segments to different lines. However, once we run CI, they're back to one line again.

@daxianji007 would know more about this.

See the history of this file for example to see how the change from November was undone after a CI run:
https://github.com/dotnet/dotnet-api-docs/commits/4e4532d3f05c95e9bdc397c505769749ef4e7252/xml/Microsoft.Build.Tasks/ResolveAssemblyReference.xml

**Comment by joelmartinez** [comment]
I'll mirror a comment that I made here: https://github.com/dotnet/dotnet-api-docs/pull/1932#issuecomment-466790967

> So this is something that's simply 100% down to the XmlDocument APIs, and how they format XML when they save … mdoc isn't doing anything special here, but these changes will always happen because those XML APIs want to format the Xml a certain way.

To add more context, this happens here:  
https://github.com/mono/api-doc-tools/blob/3f0c2fa1905aa72959db5340812fb7511ba8d379/mdoc/Mono.Documentation/MDocUpdater.cs#L554-L563

I'm not currently aware of any settings changes that I could make to the `XmlTextWriter` that would affect the Xml in the way being asked here.

... @lobrien any thoughts?

**Comment by joelmartinez** [comment]
@mairaw is the issue related to markdig specifically? or otherwise where exactly is the error being introduced ... can you describe what happens when these elements are on the same line?

Looking at the content:

```xml
<block subset="none" type="note"><para>  
 These enumerations are specified by the Visual Basic language. The names can be used anywhere in your code in place of the actual values.  
  
</para></block>
```
There doesn't seem to be any usable content in between the `para` and the `block` elements, so this should all be structural markup ... perhaps it's a parsing issue in the Ecma2Yaml plugin?

**Comment by daxianji007** [comment]
Hi @mairaw, I did those changes just aim to make the pages identical. Now I feel that it may not be mdoc issue. 

See this [dfm page](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.filesystem.getattr?view=netframework-4.7.2&branch=master#returns) and [markdig page](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.filesystem.getattr?branch=markdig-migration&view=netframework-4.7.2#returns). You can see there is almost no difference except some spaces.  **But It is weird that the `<block subset="none" type="note"><para>` content does not show in any style in both side.**

If this content is designed to show as plain text, I think we can ignore this kind of differences. If this content is designed to show in some styles, I think we`d better to fix it in template or Ecma2Yaml.

**Comment by mairaw** [comment]
It seems this made a note appear on MSDN:
https://msdn.microsoft.com/en-us/library/microsoft.visualbasic.filesystem.getattr?toc=xxx

![image](https://user-images.githubusercontent.com/12971179/54175268-6c309200-4447-11e9-99d0-2f64c2174de8.png)

We'll probably have to rewrite the content for these APIs to not rely on this anymore. I guess this diff is not blocking for the markdig migration given it's almost the same as the current page.

Should we close this PR?
