### ISSUE TITLE
Incorrect signatures for span indexers

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#422]
For example, the signatures for indexers of `Span<T>` and `ReadOnlySpan<T>` don't show correctly in API reference.

[For `Span<T>`, it shows as:](https://docs.microsoft.com/en-us/dotnet/api/system.span-1.item?view=netcore-2.0)

```cs
public T this[int index] { get; }
```

When it should be:

```cs
public ref T this[int index] { get; }
```

Original GitHub issue: https://github.com/dotnet/docs/issues/5208 by @svick

**Comment by mimisasouvanh** [comment]
Internal [bug](https://ceapex.visualstudio.com/Engineering/_workitems/edit/167409/) logged.

**Comment by huangmin-ms** [comment]
fixed in https://github.com/mono/api-doc-tools/pull/611
