### ISSUE TITLE
Duplicate content in generated XML

### ISSUE THREAD

**Issue by docs-product** [mono/api-doc-tools#424]
See [example](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Buffers/SequenceReaderExtensions.xml) - every entry is listed twice in the file. The assemblies from which we are generating the content are [here](https://apidrop.visualstudio.com/binaries/_git/binaries?path=%2Fdotnet%2Fnetcore-2.2&version=GBmaster).

**Comment by joelmartinez** [comment]
Internal item [logged](https://ceapex.visualstudio.com/Engineering/_workitems/edit/78037)

**Comment by joelmartinez** [comment]
Just double checked this ... and the issue seems to be resolved as of the latest build(s). Please let me know if this issue resurfaces
