### ISSUE TITLE
Content from parameters that differ in casing keeps getting erased after each CI run

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#427]
The following commit shows the content that I keep having to restore every time I run CI:
https://github.com/dotnet/dotnet-api-docs/pull/1957/commits/61e63039f9658eb48f0fb7c68e618b3599eef091

The only thing I see in common is that they're the same except for a different casing.

For example, PathName vs. Pathname.

**Comment by joelmartinez** [comment]
Internal item logged:  
https://ceapex.visualstudio.com/Engineering/_workitems/edit/77894
