### ISSUE TITLE
Feature request: Update _filter.xml based on `EditorBrowsableAttribute`

### ISSUE THREAD

**Issue by lobrien** [mono/api-doc-tools#428]
There is a desire from the Xamarin.Forms team that certain APIs not have IntellIiSense or Web documentation. This is controlled on docs.microsoft.com via the `_filter.xml` file. The suggestion is that this file be updated via automation. (The initial suggestion is "If `EditorBrowsableAttribute.Value == 'Never'" then add element to _filter.xml")

**Comment by joelmartinez** [comment]
Looks like this is already supported in the `_filter.xml` file! (Thanks @TianqiZhang for the info)

You can see an example here: https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/_filter.xml#L86-L94

```xml
  <apiFilter>
    <namespaceFilter name="*">
      <typeFilter name="*">
        <attributeFilter name="System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)" expose="false"/>
        <memberFilter name="*">
          <attributeFilter name="System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)" expose="false"/>
        </memberFilter>
      </typeFilter>
    </namespaceFilter>
  </apiFilter>
```
