### ISSUE TITLE
Derived classes not showing on base class documentation for nested classes

### ISSUE THREAD

**Issue by natke** [mono/api-doc-tools#430]
Example:

Base class
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.traincatalogbase.cataloginstantiatorbase?view=ml-dotnet

Derived class
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.anomalydetectioncatalog.anomalydetectiontrainers?view=ml-dotnet

Source code
https://github.com/dotnet/machinelearning/blob/0b638bfa226320099a74b5eb7e8ea5316f1843a1/src/Microsoft.ML.Data/TrainCatalog.cs#L653

**Comment by wh-alice** [comment]
@natke, tracked this issue in 85816
