### ISSUE TITLE
.NET API browser shows incorrect type descriptions for C++

### ISSUE THREAD

**Issue by Thraka** [mono/api-doc-tools#444]
_From @tmds on Thursday, October 31, 2019 2:41:30 PM_

For example [SequenceReader<T>](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.sequencereader-1?view=netcore-3.0):

```
C++

generic <typename T>
 where T : value classpublic value class SequenceReader
```

_Copied from original issue: dotnet/docs#15592_

**Comment by Thraka** [comment]
_From @Thraka on Friday, November 1, 2019 4:26:27 PM_

Thank you for letting us know. We'll investigate this.

**Comment by tmds** [comment]
> for C++

I had not noticed the language drop-down on the top right of the page.

Does the API browser default to C++?

**Comment by Thraka** [comment]
Once you select C++ it will remain C++ across the whole site until you change it. I don't know the default, I would guess C# is the default.

**Comment by tmds** [comment]
> I don't know the default, I would guess C# is the default.

That would be my expectation too. However, when I open up documentation in an 'Incognito tab' it defaults to 'C++', so I'm not sure if it is C#.

**Comment by tmds** [comment]
@Thraka what do you get in an incognito tab as the default?

**Comment by Thraka** [comment]
I get C# now. We specifically set a default now. We're unsure why it had changed to C++ in the past. I'll close this issue now.

**Comment by tmds** [comment]
Thanks @Thraka .
