### ISSUE TITLE
FrameworksIndex folder should not be empty after mdoc update

### ISSUE THREAD

**Issue by TianqiZhang** [mono/api-doc-tools#45]
With mdoc 5.0.0.9, I found that FrameworksIndex folder is empty after "mdoc update". Here's the repo step:
- Clone https://apidrop.visualstudio.com/_git/binaries to e:\mdoc\binaries
- run `mdoc.exe fx-bootstrap E:\mdoc\binaries\dotnet`, it will generate frameworks.xml under e:\mdoc\binaries\dotnet
- run `mdoc update -o E:\mdoc\mdocTest -fx E:\mdoc\binaries\dotnet\frameworks.xml` to generate xml files.
- You will find `E:\mdoc\mdocTest\FrameworksIndex` is empty, all the framework indexfiles were put under dll folder `E:\mdoc\binaries\dotnet\`

Expected behavior:
all the framework index files should be in FrameworksIndex folder.

**Comment by dend** [comment]
@joelmartinez this seems to be a non-repro for me. I chatted with @TianqiZhang yesterday and there was a mistake in passed params, so all is well 👍

**Comment by joelmartinez** [comment]
Good to hear :)

**Comment by TianqiZhang** [comment]
@joelmartinez in the release note of [preview] mdoc v5.0.0.5 the  usage of -fx parameter was demonstrated as `mdoc update -o out/path -fx path/to/frameworks/frameworks.xml`.

However @dend told me yesterday that it should be `-fx path/to/frameworks`, not including the frameworks.xml file name. Will there be an official manual about these new parameters?

**Comment by dend** [comment]
@TianqiZhang yes, I will work on putting together some documentation. We can include it in the Wiki on this project 😄
