### ISSUE TITLE
mdoc is generating C# syntax for C++ only types

### ISSUE THREAD

**Issue by TianqiZhang** [mono/api-doc-tools#46]
For example, [This class](https://msdn.microsoft.com/en-us/library/bb347663(v=vs.110).aspx) is C++ only and does not have C# syntax, however in mdoc we still see below signature:

```xml
<Type Name="ReverseBidirectionalIterator&lt;TValue&gt;" FullName="Microsoft.VisualC.StlClr.Generic.ReverseBidirectionalIterator&lt;TValue&gt;">
  <TypeSignature Language="C#" Value="public class ReverseBidirectionalIterator&lt;TValue&gt; : Microsoft.VisualC.StlClr.Generic.IBidirectionalIterator&lt;TValue&gt;" />
```

Similar issues were found for VisualBasic too.

**Comment by jonpryor** [comment]
I don't understand the issue.

1. There's no way of knowing what language an assembly was generated in, and
2. Even if there was a way, who cares? *The whole point* to managed code is that it's language agnostic; if it's IL, your C++ code can be invoked from C# code, and consequently there is a "C# declaration" for the member.

Indeed, [look at the MSDN page you linked to](https://msdn.microsoft.com/en-us/library/bb347663(v=vs.110).aspx?cs-save-lang=1&cs-lang=vb#code-snippet-1): it provides declarations for C#, C++, F#, and VB:

> * **C#**:
> 
>         public class ReverseBidirectionalIterator<TValue> : IBidirectionalIterator<TValue>
> 
> * **C++**: 
> 
>         generic<typename TValue>
>         public ref class ReverseBidirectionalIterator : IBidirectionalIterator<TValue>
> 
> * **F#**:
> 
>         type ReverseBidirectionalIterator<'TValue> = 
>             class
>                 interface IBidirectionalIterator<'TValue>
>             end
> 
> * **VB**:
> 
>         Public Class ReverseBidirectionalIterator(Of TValue)
>         	Implements IBidirectionalIterator(Of TValue)
>

**Comment by joelmartinez** [comment]
AS @jonpryor mentions, this is expected behavior. We already have an issue (#10) to add additional signatures such as F# :)
