### ISSUE TITLE
In frameworks mode, mdoc should not mark any types as removed if they exist in another framework

### ISSUE THREAD

**Issue by TianqiZhang** [mono/api-doc-tools#53]
When running againse existing xml files, "mdoc update" will rename some types to ".remove" if they don't exist in newer frameworks.

That's not expected because in -fx mode, we have the framework index files to tell which type belongs to which framework, so none of the types should be "removed".

**Comment by TianqiZhang** [comment]
Take `System.Windows.Markup.WhitespaceSignificantCollectionAttribute` for example, it existed in .Net framework 3.0, 3.5 and 4.0. However after mdoc update, its xml file was renamed to .removed.

**Comment by joelmartinez** [comment]
Hmm ... so far in my tests, I haven't been able to reproduce this. I modified a test to run multiple times, with types that exist in different frameworks only.

**Comment by joelmartinez** [comment]
Ok ... I was finally able to reproduce this successfully. Will address now
