### ISSUE TITLE
[mdoc] Missing types on running mdoc in Frameworks Mode

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#55]
Download the binaries repo, and use `netframework-4.6` as an example. We have `mscorlib.dll` that contains the primary types there

Now, if I run a standard `mdoc update mscorlib.dll -o SOME_LOCATION`, I get the `System` folder, and a `String.xml` in it

However, now say I run `mdoc fx-bootstrap FOLDER_WHERE_NET_FRAMEWORK46_IS`

Then `mdoc update -fx FOLDER_WHERE_NET_FRAMEWORK46_IS -o TEST_LOCATION`

It completes the work BUT now `String` is nowhere to be found. It's not in `FrameworksIndex` and it's not in any of the folders

**Comment by joelmartinez** [comment]
This seems like it might be related to #21 ... @dend, are you keeping a copy of the output log when you run into this problem by chance? I'd love to be able to search through it and see if any errors are reported at any point

**Comment by joelmartinez** [comment]
Finally! was able to recreate this issue, and really it's just a manifestation/sideeffect of #53. Going to close this issue and it will be resolved there. Thanks @dend, your tip on reproducing the issue really helped in finding it!
