### ISSUE TITLE
[mdoc] Support of reflecting EXE files in Frameworks Mode

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#58]
Some tools provide Windows executables that need to be documented. Would be great to have support for EXE reflection in Frameworks mode - this is already something that is supported in the independent DLL/EXE mode.

**Comment by joelmartinez** [comment]
@dend since frameworks mode takes a bit of a "wildcard" search approach for `*.dll` files ... should I simply add `*.exe` to the list of files that are processed? or are you thinking this is more of a selective approach where we'd have to list the EXEs in the `frameworks.xml` file?

**Comment by dend** [comment]
@joelmartinez I think a flag of some sort that says `--includeexe` would work. That way, you get blanket coverage, but also are not forcing those by default.

**Comment by dend** [comment]
@joelmartinez I would cut this because it's an edge case and we don't need it anytime soon.

**Comment by dend** [comment]
Per earlier discussion, this is not a priority.
