### ISSUE TITLE
mdoc is inserting invalid parameter type name

### ISSUE THREAD

**Issue by TianqiZhang** [mono/api-doc-tools#59]
In the xml generated for .Net class System.Printing.IndexedProperties.PrintTicketProperty, you can see below member:

```xml
<Member MemberName="op_Implicit">
      <MemberSignature Language="C#" Value="public static System.Printing.PrintTicket op_Implicit (System.Printing.IndexedProperties.PrintTicketProperty modreq(System.Runtime.CompilerServices.IsImplicitlyDereferenced) attribRef);" />
      <MemberSignature Language="ILAsm" Value=".method public static hidebysig specialname class System.Printing.PrintTicket op_Implicit(class System.Printing.IndexedProperties.PrintTicketProperty modreq(System.Runtime.CompilerServices.IsImplicitlyDereferenced) attribRef) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Printing.IndexedProperties.PrintTicketProperty.op_Implicit(System.Printing.IndexedProperties.PrintTicketProperty|System.Runtime.CompilerServices.IsImplicitlyDereferenced)~System.Printing.PrintTicket" />
      <MemberType>Method</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Printing</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute>
          <AttributeName>System.Security.SecuritySafeCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Printing.PrintTicket</ReturnType>
      </ReturnValue>
      <Parameters>
        <Parameter Name="attribRef" Type="System.Printing.IndexedProperties.PrintTicketProperty modreq(System.Runtime.CompilerServices.IsImplicitlyDereferenced)" />
      </Parameters>
      <Docs>
        <param name="attribRef">To be added.</param>
        <summary>To be added.</summary>
        <returns>To be added.</returns>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
```

Not the `<Parameter Name="attribRef" Type="System.Printing.IndexedProperties.PrintTicketProperty modreq(System.Runtime.CompilerServices.IsImplicitlyDereferenced)" />`, it's not a valid type string

**Comment by dend** [comment]
This came up again, and it looks like it's affecting around 3K APIs in the .NET universe, because of how we mix .NET platform and Xamarin.

**Comment by joelmartinez** [comment]
This is the member in question on MSDN (for my own reference): https://msdn.microsoft.com/en-us/library/ms552863(v=vs.110).aspx 

@dend ... can you give me a bit more detail about how this involves .net/xamarin?

**Comment by joelmartinez** [comment]
@dend, Since you can't represent `modreq` and `modopt` in C#, and the corresponding MSDN reference page lists the signature as:

```csharp
public static implicit operator PrintTicket (
	PrintTicketProperty attribRef
)
```
Is it fair to say that mdoc should simply ignore these two attributes and omit them from any C# signature?

**Comment by dend** [comment]
@BillWagner @mairaw can you please comment on @joelmartinez 's statement above?

**Comment by BillWagner** [comment]
I believe @joelmartinez is correct: mdoc can ignore `modopt` and `modreq` in API signatures.

i'd like either @jaredpar or @madstorgersen to verify.

**Comment by jaredpar** [comment]
At this point C# doesn't make use of `modreq` or `modopt` for features but it will begin doing so in 7.2. In particular `modreq` will be used to distinguish between scenarios where we have `ref` and `ref readonly`. The latter will use a `modreq`. 

Outside of that though @joelmartinez statement is correct: C# can't represent `modopt` and `modreq` directly and hence can be largely ignored when generating signature for **display** purposes.

**Comment by joelmartinez** [comment]
I've got this working, but am looking to make my unit tests a bit more robust. Currently, I'm testing with the following c++/cli [class](https://github.com/mono/api-doc-tools/blob/mdoc-mods/mdoc/mdoc.Test/cppcli/cppcli/cppcli.h):

```cpp

	public class SomeClass {};

	public interface class SomeInterface  {
	public:
		SomeClass& SomeFunc2(SomeClass param) = 0;
		int SomeFunc(volatile SomeClass* param) = 0;
		SomeClass** SomeFunc3(int param) = 0;
		int SomeFunc4(SomeClass*& param, volatile int param2) = 0;
	};
```

@jaredpar, @BillWagner, @dend ... I would love any additional scenarios you can think of for testing modifiers  :) Are there any other instances you can think of that would generate modopt/modreq in the metadata other than `&`/volatile?

**Comment by jaredpar** [comment]
I believe `const` also generates `modreq / modopt`.

**Comment by joelmartinez** [comment]
Ahh. I believe my implementation will catch this, but I will add this additional unit test just to make sure. Thanks for the feedback @jaredpar :)

**Comment by meganbradley** [comment]
@joelmartinez Great news! Is there an ETA for when the testing will be done and we can re-run mdoc?
CC @mairaw.

**Comment by joelmartinez** [comment]
@meganbradley Hi ... I actually did do a release (I updated @dend), unfortunately, there is still an issue with updating existing EcmaXML that had nodes using the old operator signatures (tracked here #107). So I will have to do another small release with the fix for that. Hopefully this week.

**Comment by dend** [comment]
This issue still seems to be active:
https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configuration.getsection?view=netframework-4.7#System_Configuration_Configuration_GetSection_System_String_

Notice that the parameter in the signature is different than the one in the `Parameters` section.

**Comment by joelmartinez** [comment]
@dend I think that might be a separate issue? yes I see that the parameters are named differently, possibly because they have different parameter names in `System.Configuration.dll` vs `System.Configuration.ConfigurationManager.dll`

**Comment by mairaw** [comment]
Probably they do have different names in the different DLLs. But then the tool should probably pick one and stick with that no?

Right now it mixes and matches both like here:
![image](https://user-images.githubusercontent.com/12971179/30445895-627e0682-993c-11e7-92bc-4262aed9087b.png)

**Comment by joelmartinez** [comment]
@mairaw agreed ... but that's still not technically related to this issue at all :) probably needs a new issue to track, as we'll probably have to do something `AlternateFramework` attributes

**Comment by mairaw** [comment]
I think from @dend comment on, we started tracking as if it was the same issue I guess. I'll open a new one then.

**Comment by joelmartinez** [comment]
@mairaw precisely, that is correct. There is a batch of changes that is (roughly) next on the roadmap, which address these kind of divergent elements in various frameworks. I'm *hoping* to address a number of them for each release in that timeframe. Will definitely be a topic of conversation between @dend and I to coordinate other dependencies :)
