### ISSUE TITLE
[ecmaxml] Support for <see href="" />

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#62]
We need a constrained way to support external links.

`<see href="https://microsoft.com">Test Link</see>` would be perfect for the job.

**Comment by jonpryor** [comment]
I'm not sure that we want to "overload" `<see/>` for this purpose; what should happen with?

    <see cref="T:System.String" href="http://example.com">Link text</see>

I think a new element might be better, likely `<a/>`.

Random aside: does anybody know why the original C# XML documentation comments chose `<para/>` for paragraphs and not `<p/>`? Would it be *bad* to be more similar to (X)HTML?

**Comment by joelmartinez** [comment]
heh ... I went back and forth with myself over this very question. What I ultimately came to ... and I'm very willing to have my mind changed and go with consensus, is that while `<a/>` is logical, it also comes with certain expectations from users. So once they can do `<a href`, they'll want to introduce `<a name` anchors, and maybe they want to use a specific HTML style so they try `<a class`.

And it could be that all of those things are good and that we should support them ... but `<see` already supports two attributes, `cref` and `langword`. I think it makes sense that `<see href` would be an external link in this case without conferring other potential uses to the user.

Like I said ... definitely open to further thoughts on this, @jonpryor :)

**Comment by jonpryor** [comment]
I'd forgotten about `//see/@langword`. I'm still not sure about allowing `<see/>` to have element content.

Assuming we do use `<see/>`:

1. Do we want to use `@href` and not something without HTML considerations? (Which is counter to what I previously said, but if the intent is to avoid "confusion", do we want to suggest a `@rel` attribute? `@target`? `@hreflang`? `@type`?)

    Perhaps `@uri`?

2. How far down the rabbit hole do we want to go here? `monodoc.dll` already has support for [rending man pages](http://docs.go-mono.com/?link=man%3amdoc(5)). Would it be plausible to want:

        <see uri="man:mdoc(5)" />

    and have that link somewhere "appropriate"?

Related: I've long pondered having `man` page output for ECMA XML. Probably silly, but allows a mental model of "divorcing" the XML from the rendering context. How should `<see uri="example" />` be handled with man-page output?

**Comment by joelmartinez** [comment]
I'd advocate for `@href` ... _Hypertext REFerence_ communicates exactly what we expect in here.  re `#2`, the `@href` would simply be handed off to the host. So on the web it's handled by the browser, in the native viewer via [`LoadUrl`](https://github.com/xamarin/macdoc/blob/2a23455108ea8226f17d5d21007cb95f1e41dc65/MyDocument.cs#L236).

**Comment by MichaelNorman** [comment]
Currently, we put links in by escaping to HTML with `<format type="text/html"><a href...</a></format>`. It ain't great, but there is a workaround. Just chiming in for completeness.

Also: Yes, `<para>` is stupid.

**Comment by joelmartinez** [comment]
> Also: Yes, <para> is stupid.
Sounds like someone wants to [open a new enhancement request](github.com/mono/api-doc-tools/issues/new) ;)

**Comment by jonpryor** [comment]
I think it's too late to ditch `<para/>` now. Alas.

**Comment by joelmartinez** [comment]
Implemented in this PR https://github.com/mono/api-doc-tools/pull/74
