### ISSUE TITLE
[mdoc] No support for attached events

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#63]
Currently, `mdoc` does not support treating attached events as members, which causes loss of data when reflecting from .NET assemblies.

As an example of an attached event:
https://msdn.microsoft.com/en-us/library/system.windows.dragdrop.dragover(v=vs.110).aspx

**Comment by joelmartinez** [comment]
Ahh, yes ... this is something that has come up in the past and is definitely necessary. Ok, so below I present a proposal:

1. Look at the list of members on a type for the pattern and for each combination of the following members: 
    - `RoutedEvent {name}Event`
    - `void Add{name}Handler(DependencyObject,RoutedEventHandler)`
    - `void Remove{name}Handler(DependencyObject,RoutedEventHandler)`
1. Create a new `Member` node in the type XML, with
    - `MemberName="{name}"`
    - `<MemberType>AttachedEvent</MemberType>`
    - a `MemberSignature` that is `see Add{name}Handler, and Remove{name}Handler`, for all signature types (C#, ILAsm, currently).

The member node would look as such (_using `Thing` in place of the `{name}` placeholder used above_)

```xml
    <Member MemberName=".ctor" apistyle="unified">
      <MemberSignature Language="C#" Value="see AddThingHandler, and RemoveThingHandler" />
      <MemberSignature Language="ILAsm" Value="see AddThingHandler, and RemoveThingHandler" />
      <MemberSignature Language="DocId" Value="A:TheNamespace.TheType.Thing" />
      <MemberType>AttachedEvent</MemberType>
      <Docs>
        <summary>To be added.</summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
```

*question*, should additional information be placed in the xml to facilitate rendering of routed event information (as in the image below, from the link above)?
![image](https://cloud.githubusercontent.com/assets/90380/24715698/6c8f3072-19fa-11e7-9fa5-7fba2b449576.png)


For myself, here are a few implementation notes with links to the code where it should be updated.

- A new "prefix" would be implemented for the `EcmaUrlParser`
    - `A` for AttachedEvent.
    - in the form of `A:Namespace.Type.{name}`
    - this has a dependency on #20 
- mdoc would be modified
   - [`DocumentationEnumerator.GetDocumentationMembers`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/monodocer.cs#L3513)
   - [`MdocUpdater.DoUpdateType2`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/monodocer.cs#L1224)
   - [`MdocUpdater.UpdateMember`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/monodocer.cs#L1832)
- Monodoc would be modified so these new URLs are supported
   - [`EcmaProvider.CanHandleUrl`](https://github.com/mono/api-doc-tools/blob/master/monodoc/Monodoc/providers/ecma-provider.cs#L219)
    - [`EcmaDoc.GetContextForEcmaNode`](https://github.com/mono/api-doc-tools/blob/master/monodoc/Monodoc/providers/EcmaDoc.cs#L370)
    - [`EcmaDoc.EtcKindToCaption`](https://github.com/mono/api-doc-tools/blob/master/monodoc/Monodoc/providers/EcmaDoc.cs#L461)
    - [`EcmaDesc.Kind`](https://github.com/mono/api-doc-tools/blob/42950d5b1af0b7107118a0ef8f4e74218cc1dfba/monodoc/Monodoc.Ecma/EcmaDesc.cs#L13)

Adding a few other folks for FYI and discussion, as this has been discussed in the past: @conceptdev, @charlespetzold, @MichaelNorman, @jonpryor

**Comment by MichaelNorman** [comment]
From  https://msdn.microsoft.com/en-us/library/ms742806(v=vs.110).aspx :

> Extensible Application Markup Language (XAML) defines a language component and type of event called an attached event. The concept of an attached event enables you to add a handler for a particular event to an arbitrary element rather than to an element that actually defines or inherits the event. In this case, _neither the object potentially raising the event nor the destination handling instance defines or otherwise "owns" the event._ (Emphasis mine.)

Insofar as the relationship _is not_ in the assembly, no information _is lost_ during reflection, correct? A better approach, in my mind, is to generate boilerplate remarks to each of the pieces that indicate that these three methods constitute the "Thing" attached event. I don't think that clobbering the declaration syntax with fake "see" clauses from imagined `<see cref=... />` references was a good choice on MS's part. This really does seem like a XAML thing, and trying to cover it in .NET docs in this way seems like a hack.

I definitely disagree with the `A:` prefix, as attached events do not map to .NET language features, such as properties, methods, or fields. It's a combination of a language feature _and_ the type hierarchy _and_ implementation details.

**Comment by dend** [comment]
@MichaelNorman @joelmartinez this is indeed a XAML thing, and I think it's fair to say that we should just add a remark that says it's an attached event.

**Comment by TianqiZhang** [comment]
@dend @joelmartinez we should also consider attached properties for XAML.

**Comment by mijacobs** [comment]
Here's how to detect an attached property:

- Class X has a static field of type DependencyProperty  with the name <property>DependencyProperty.
- Class X also has one or two of static methods with the following name: Get<property> or Set<property>

- The Get<property> method takes one argument of type DependencyObject (or something IsAssignableTo(DependencyObject), and returns a value of type dp.PropertyType (or IsAssignableTo…), where dp is the value of the static field.

- The Set<property> method takes two arguments.  The first has type DependencyObject (or IsAssignableTo…), the second has type dp.PropertyType (or IsAssignableTo…).  It returns void.

**Comment by dend** [comment]
@joelmartinez is this something that we can implement in `mdoc` based on the descriptions from @mijacobs ?

**Comment by joelmartinez** [comment]
@dend, yes, the same general approach as my [earlier proposal](https://github.com/mono/api-doc-tools/issues/63#issuecomment-291916158) can be used for attached properties *and* attached events; with one change ... instead of using a different prefix for the mdoc URL (which complicates the task a bit due to the dependency on #20), the email discussion suggested just re-using the existing ones (presumably `E:` for the attached event and `P:` for the attached property?) to match the existing asset ids. 

I think that's a workable idea (if you can verify what prefixes we should use, @dend).

**Comment by mairaw** [comment]
Yes, @joelmartinez please use E: for attached events and P: for attached properties. That's what VS/IntelliSense already use.

For example:
![image](https://user-images.githubusercontent.com/12971179/30833488-23f5746a-a204-11e7-97d6-40c6b1471a57.png)

If it helps, I can provide you with a list of all attached events and properties I'm expecting to see for the .NET Framework.

/cc @dend
