### ISSUE TITLE
monodoc-ecma.xsd does not reflect current usage

### ISSUE THREAD

**Issue by lobrien** [mono/api-doc-tools#71]
The monodoc-ecma.xsd in mdoc/Resources is missing some elements / attributes that are broadly used in our existing (large) monodoc directories. Importantly, it is missing `apistyle`, `attribution`, and`tool`. 

If we are to move towards broader usage of monodoc / mdoc, we need to, at the least, have an accurate set of type definitions.

**Comment by joelmartinez** [comment]
This is resolved in https://github.com/mono/api-doc-tools/pull/72 (when that is merged) ... follow that PR for status
