### ISSUE TITLE
[mdoc] Support NuGet information in the frameworks.xml file

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#81]
When bootstrapping in frameworks mode, allow also adding NuGet information to bind a certain API to it. This goes hand-in-hand with #80

**Comment by dend** [comment]
@joelmartinez here I am curious if we can just end up with just the NuGet information bundled in the frameworks index XML file. Effectively, per moniker specify that a given API set is bundled in a package (ID + version). That way, #80 would be redundant (we don't need to embed anything in the actual type/NS XMLs) as any parser would just read in the frameworks index.

**Comment by joelmartinez** [comment]
@dend, can I get confirmation that this is the direction you want to go? if so, I can close #80. 

Additionally, is this as simple as adding something like `<nuget>the-nuget-id</nuget>` as a child to the `<Framework>` node ... or is there other information that you need tracked in here?

**Comment by katebialiatka** [comment]
Hello,
I have some questions in regards to this issue. Could you please comment on them?

1. Could you please shed a light what is a 'framework mode'? How does it differs from usual update mode? Is my understanding correct that program searches  for assemblies in directories specified in `'framework.xml'` file and next apply common logic?

2. Could you please share an example of` 'framework.xml'` file?

3. I assume, Nuget info needs to be grabbed from **.nuspec** file. Who (or which system) will be responsible for populating nuget info to the` 'framework.xml'` file and how this will look like? Or do we need to read **.nuspec** file which will be located in a folder listed in 'framework.xml' to get Nuget info?

4. Is it correct that this ticket is dedicated to read Nuget info (id + version) and just put it to the index.xml output file? Format can be` <nugetInfo><id> </id> <version> </version></nugetInfo>`

**Comment by joelmartinez** [comment]
@katebialiatka yes, this is a good indication that I need to write some documentation on frameworks mode (@dend and his team are the first users of this functionality really, so I haven't had to communicate it much to 3rd parties yet).

1. a great question ... you can find more information about frameworks mode and how to use it in some of the previous release notes, for example [5.0.0.5](https://github.com/mono/api-doc-tools/releases/tag/preview-5.0.0.5). In a future release, I also added the ability to reference import documentation in frameworks mode ([5.0.0.15](https://github.com/mono/api-doc-tools/releases/tag/preview-5.0.0.15)).
1. see above point
1. I would like to see this same info from @dend ... for him to propose how they want to use the feature and what data needs to be included (nuget id and version?). Additionally, it might suggest a parallel task, that `.nuspec` file should be considered in the `mdoc fx-bootstrap` subcommand.
1. I'm ok with this format proposal ... if that works for @dend and his team.

**Comment by joelmartinez** [comment]
@katebialiatka additionally, you can always look at the integration tests, where I try to make sure all major features are represented. For example, "frameworks mode" has several tests in the makefile, such as [`check-monodocer-frameworks`](https://github.com/mono/api-doc-tools/blob/preview-5.0.0.15/mdoc/Makefile#L147). Looking at those and becoming familiar with the integration tests is a good way to see tons of examples of how to use mdoc :)

**Comment by dend** [comment]
@joelmartinez yes, I believe a single place of reference is the way to go here, and a lot of other richer experience (e.g. links) would be post-processed. What I want to make sure is that we track the package ID and package version.

**Comment by joelmartinez** [comment]
In that case since there's more than one piece of data, let's maintain consistency with existing tools, and simply use the exact same tag and attributes as the `packages.config` file. So, something like:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Frameworks>
  <Framework Name="One" Source="One">
    <assemblySearchPath>dependencies/One</assemblySearchPath>
    <package id="thepackage" version="2.2.2" />
  </Framework>
</Frameworks>
```

@dend, can you confirm that this is all you're looking to achieve? do you want this data propagated to any of the framework index files?

**Comment by dend** [comment]
@joelmartinez the above looks good to me. Can we include this in individual framework index files for monikers in the same format, as `<package id="thepackage" version="2.2.2" />`?

**Comment by joelmartinez** [comment]
@dend, sure :) 

Implementation notes: 

- look at the constructor for [`AssemblySet`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/Updater/Frameworks/AssemblySet.cs#L24) ... we'll want to add an additional parameter to accept and store this new nuget information when we read it from the xml.
- That information should then be passed to [the `FrameworksIndex` class here](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L551) ... you'll have to add a method to add the info to a list or dictionary member in the `FrameworkIndex` class (accessible via `this.frameworks`
- And lastly, write out the information in [`FrameworkIndex.WriteToDisk`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/Updater/Frameworks/FrameworkIndex.cs#L53)

**Comment by asokolovskiy15** [comment]
@joelmartinez I'm investigating this issue and have some question in regards to it:

According to the title and first message, we should add information about NuGet to `framework.xml` file.
To do this we need to edit  [`Run`](https://github.com/mono/api-doc-tools/blob/preview-5.0.0.15/mdoc/Mono.Documentation/frameworksbootstrapper.cs#L16) method for the command `fx-bootstrap`.

However in your last comment, you described another flow - running update command with `-frameworks` parameter. As a result NuGet info will be added to [FolderName].xml file (not to `framework.xml` as was stated in the title). Is there a chance, that  your flow relates to ECMAXML file which initially should be covered with another issue #80 (issue #80 was closed)?

Could you please clarify which of this approaches should be covered with the current ticket?

**Comment by joelmartinez** [comment]
@asokolovskiy15 yes, I agree that it's a little confusing, as the proposals have evolved over time; my apologies for that. The original idea with #80 was to put this information in each type/member node (which IMO would have been too duplicative). 

So, the latest proposal for this issue is as described in [this comment](https://github.com/mono/api-doc-tools/issues/81#issuecomment-335849136) ... the `package` node will be (optionally) in the frameworks.xml. If it's present, it will be read, and propagated to the framework index xml file.

**Comment by asokolovskiy15** [comment]
@joelmartinez ok, but how will NuGet info be populated to the `framework.xml`

As I can see this, ticket may consist of 2 parts to be implemented by me.
1 part: Read `.nuspec` file and fill `framework.xml` with NuGet info during `fx-bootstrap` command.
2 part: Apply solution from [this comment](https://github.com/mono/api-doc-tools/issues/81#issuecomment-335849136)

Should we do first part? And If first part should be done inside this ticket, could you please specify where `.nuspec` file will be located?

**Comment by joelmartinez** [comment]
@asokolovskiy15 oh ... actually, upon reading [my comment](https://github.com/mono/api-doc-tools/issues/81#issuecomment-334496081), that exact requirement is still pending more information/comment from @dend. I don't know whether the expectation is that you're reading a `.nuspec` file, or that you have to unzip the `.nupkg`.

But to answer your question, yes, if @dend says that `fx-bootstrap` has to read and insert this information into the `frameworks.xml` you'll have do it in this ticket. Just wait for his feedback on whether we're reading from nuspec or nupkg, and where it/they will be located.

**Comment by dend** [comment]
@asokolovskiy15 @joelmartinez I don't think `mdoc` should be reading any NuGet files at all - we just want the ability to specify, in the `frameworks.xml` file, the fact that the API has an associated NuGet package, with package ID and version.

When `mdoc` runs and builds out the `FrameworksIndex`, it should include the respective NuGet information there.

**Comment by joelmartinez** [comment]
Oh I see ... so then there's no change to the `fx-bootstrap` subcommand. The entry of the `package` node in `frameworks.xml` will be manual ... and `mdoc update` will simply read it and write it to the frameworks index file. Thanks for the clarification @dend!
