### ISSUE TITLE
[mdoc] Operator marking might not be interpreted correctly

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#82]
As an example, we have the [Addition](https://msdn.microsoft.com/en-us/library/system.decimal.op_addition(v=vs.110).aspx) operator. If we look at the current signature on MSDN, we see:

```
public static decimal operator +(
	decimal d1,
	decimal d2
)
```

The same page on [docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/api/system.decimal.op_addition?view=netframework-4.7) is showing:

```
public static decimal op_Addition (decimal d1, decimal d2);
```

If we look at the [ECMAXML content](https://github.com/dotnet/docs/blob/master/xml/System/Decimal.xml#L1634):

```
<MemberSignature Language="C#" Value="public static decimal op_Addition (decimal d1, decimal d2);" />
````
There seems to be a mismatch, as we are getting the IL representation vs. the "true" C# one.

**Comment by joelmartinez** [comment]
@jonpryor this seems like a straightforward request ... can you provide any insight on why this may have been implemented this way, or potential problems in changing it?

**Comment by jonpryor** [comment]
@joelmartinez: Nope, I don't remember. We should do this.

**Comment by joelmartinez** [comment]
For implementation reference, here is the list of overloadable operators:    
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/overloadable-operators

The modifications for this will probably come to the [`CSharpFullMemberFormatter.AppendMethodName`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/monodocer.cs#L5503) method.

**Comment by joelmartinez** [comment]
This work is in progress ... leaving another reference detail, the list of operator overload method names is surprisingly difficult to find; the list of overloadable-operators in the comment above doesn't actually tell you the name of the method emitted by the compiler.

You *can* find this information in the Roslyn Source Code: https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/Core/Portable/Symbols/WellKnownMemberNames.cs

But that's not very easy to read. I did find this stackoverflow answer that listed them nicely :)

https://stackoverflow.com/a/36578459/5416
```
Outside of Order of Operations (used when necessary to coerce types)
   op_Implicit
   op_True
   op_False

Unary (only one operator)
++ op_Increment (Includes preincrement and postincrement)
-- op_Decrement (Includes predecrement and postdecrement)
-  op_UnaryNegation
+  op_UnaryPlus
!  op_LogicalNot
~  op_OnesComplement
   op_Explicit
await (Not overloadable)

Multiplicative
/  op_Division
%  op_Modulus
*  op_Multiply

Additive
+  op_Addition
-  op_Subtraction

Shift
<< op_LeftShift
>> op_RightShift

Relational
>  op_GreaterThan
<  op_LessThan
>= op_GreaterThanOrEqual
<= op_LessThanOrEqual
as (Not overloadable)
is (Not overloadable)

Equality
== op_Equality
!= op_Inequality

And
&  op_BitwiseAnd

Exclusive Or
^  op_ExclusiveOr

Inclusive Or
|  op_BitwiseOr

Conditional And
&& (Not overloadable - use "implicit operator bool" or "operator true")

Contional Or
|| (Not overloadable - use "implicit operator bool" or "operator true")

Null-Coalescing Operator
?? (Not overloadable)

Ternary
?: (Not overloadable - use "implicit operator bool" or "operator true")

Assignment
=  (Not overloadable - for combined operator and assignment (such as +=), just use the operator (+))
```

**Comment by dend** [comment]
@mairaw @BillWagner - could you please take a look at the above and confirm that these are an accurate representation of operators?

**Comment by BillWagner** [comment]
I have one correction (which may not apply for MDoc:

Assignment is not overloadable. However, the effect of overloaded assignment can be achieved by implicit conversion operators.

For example:

```csharp
int val = 5;
string s = val;
```

Would be valid iff either `string` or `int` defined a conversion operator:

```csharp
public class int
{
   public static implicit operator string(int value) =>
        value.ToString();
}
```
Otherwise, it's correct. The correct IL names are mapped to the correct C# names.

**Comment by joelmartinez** [comment]
Thanks @BillWagner ... I'm writing some implicit/explicit conversion operator tests now. All the unit tests for the other operators are already green :) 

![image](https://user-images.githubusercontent.com/90380/28640933-5eff3e6a-721b-11e7-9cfe-0c6a321c36b8.png)

**Comment by dend** [comment]
Thanks @BillWagner & @joelmartinez - love the collaboration here.
