### ISSUE TITLE
"Works With" API Tracker

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#85]
One of the items that we are looking into building for the API Browser right now is the ability to track APIs that "work with" other APIs. As an example, a number of Azure NuGet packages are released in versions for .NET Core, .NET Standard, .NET Framework, Xamarin, etc.

We need a way to represent this relationship in the ECMAXML-generated content. There are several ways we can approach them, one of them being something similar to what is done with `FrameworksIndex` where we have something like `InteropIndex` that defines what APIs "work with" a particular set of other APIs.

**Comment by joelmartinez** [comment]
A few clarifying questions:

1. Are these interop targets == framework identifier?  
  _thought: it feels like the concept of the identifier is being overloaded to mean: platform, clr variant, and now nuget package_
1. Is this solely for APIs distributed through Nuget?  
  _thought: Isn't this information more appropriately (and up to date) contained in the nuget feed/package itself? should we be duplicating this information?_
1. What constitutes "works with" ... is this information available in the assembly metadata, or will mdoc have to start parsing nuget packages?
1. Are there constraints on what can work with what else? is it only nuget package->works with->clr variant/platform? or can it be something like ".NET Standard 2 works with iOS"?

**Comment by dend** [comment]
Answering each.

1. Yes. Effectively, we are looking for a way that says "this API is designed **for this other** API". We are not necessarily tying this to a NuGet package or any entity for that reason, other than an existing platform identifier and the associated set of APIs.

2. Nope, this should apply to any managed API that we work with through mdoc.

3. I don't think this is something that we need to parse out - just have the ability to specify that in the configuration, the same way we do for frameworks today.

4. It should always bind to a product ID (e.g. an existing API)

Adding @sampy to the conversation as well, given that we discussed some of this with him before.

**Comment by joelmartinez** [comment]
I see ... thanks for the clarification. Ok, so to start the conversation, you mentioned that you would want to define this relationship in the configuration file. So what if we had a frameworks.xml file that looked like:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Frameworks>
  <Framework Name="OneFX" Source="OneFX">
    <assemblySearchPath>dependencies/OneFX</assemblySearchPath>
  </Framework>
  <Framework Name="OtherFX" Source="OtherFX">
    <assemblySearchPath>dependencies/OtherFX</assemblySearchPath>
    <Targets>
      <WorksWith Name="OneFX" />
    </Targets>
  </Framework>
</Frameworks>
```
And then in the output after running a frameworks update, we would end up with an XML file in `FrameworksIndex/InteropIndex.xml` that would look like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Frameworks>
  <Framework Name="OtherFX">
      <WorksWith Name="OneFX" />
  </Framework>
</Frameworks>
```
This would basically just be the dependency graph derived from the `frameworks.xml` file data ... including only frameworks that "work with" another framework.  Alternatively, this data structure could be inverted ... 
```xml
<?xml version="1.0" encoding="utf-8"?>
<Frameworks>
  <Framework Name="OneFX">
      <Dependent Name="OtherFX" />
  </Framework>
</Frameworks>
```
Thoughts?

**Comment by Sampy** [comment]
I think that works for most cases but in some instances the supported data is actually per namespace, class, or method. 

For example, the Azure Key Vault configuration provider nuget package supports both .Net Core and the .Net Framework. The configuration provider has three constructors. Two take a client ID and secret but one takes a client certificate as an X509Certificate2 object. The first two are supported on both Core and Framework but the third is only supported on the full Framework since Core doesn't have APIs that the third constructor needs on X509Certificate2.

Since we need the "runs on" at a member level, I was thinking something that looks almost exactly like the current frameworks XML format (top level moniker then a full tree of Namespace->Type->Member) would be what we needed.

**Comment by joelmartinez** [comment]
Thanks for the clarification @Sampy. Hmm ... I can see what you're referring to; however I think we might be at risk of making things a bit more confusing than they need to be. 

Given your description ... it feels incredibly similar to how we originally handled the BCL. There are different "shapes" to the library on different frameworks. Thus, when we run `mdoc update`, we include every version of the assembly as being assigned to a given framework (thus frameworks xml, the framework index files, etc.)

Unfortunately, it seems like we may have gone too far in this direction; diluting the meaning of "framework" to not only mean .net (full), .net core, .xamarin.ios, xamarin.android,etc. ... but *also* to mean individual libraries such as `Azure.Batch`, and `Microsoft.Azure.KeyVault`
![image](https://user-images.githubusercontent.com/90380/26987560-01eac8e6-4d1a-11e7-8f75-1f20db6ad790.png)

We need to take a step back and reconsider how we're organizing these sets of documentation. Logically ... when you run `mdoc update` in frameworks mode, the idea is that you're updating a *single* _logical_ library. For example, the .net BCL ... thus, the "frameworks" in that case are as I mentioned before, ".net core", ".net full", "xamarin.ios", etc. Take a look at the words you're using, even

> For example, the Azure Key Vault configuration provider nuget package supports both .Net Core and the .Net Framework. The configuration provider has three constructors. Two take a client ID and secret but one takes a client certificate as an X509Certificate2 object. The **first two are supported on both Core and Framework** but the third is **only supported on the full Framework** since Core doesn't have APIs that the third constructor needs on X509Certificate2.

This is the exact use case that "frameworks mode" was meant to address. If you run `mdoc update --frameworks` on the Azure Key Vault nuget/library *separately* from any other library, then the `frameworks.xml` file can represent every version of the library ... the one as it exists for .net core, the one as it exists for .net full, etc. And again, a single "library" can contain multiple assemblies as the BCL does. And in the case of Azure, perhaps you want to group all of the Azure-related assemblies into one doc set.

I understand that I'm probably asking for some non-trivial refactors on your end ... but as currently described, I think we're going down the wrong path. But of course, am always open to discussion and additional clarification if I'm not understanding something correctly :)

**Comment by dend** [comment]
@joelmartinez system-wise, we are grouping individual sets of packages as a "framework" (e.g. all Azure), but we allow per-moniker selection to pick individual packages to the _end-user_ (e.g. show me APIs in KeyVault).

If I am interpreting you correctly, what you are suggesting is **using the frameworks mode** on top of something like:

```
azure-keyvault
|___ azure-keyvault for .NET Core 2.0 version 3.7
|___ azure-keyvault for .NET Core 1.0 version 3.7
|___ azure-keyvault for .NET Framework 4.5 version 3.7
```

In this case, we still need some sort of binding to **what framework** it is **designed for** from **the list of existing frameworks**. And the list of existing frameworks can be pre-defined (e.g. all .NET Framework releases, etc.).

**Comment by dend** [comment]
@Sampy to comment on the proposal

**Comment by joelmartinez** [comment]
@dend and @Sampy, after our discussion, here's what I'm thinking:

in `frameworks.xml`, we can wrap the `Frameworks` tag in a `Versions/Version` ... 

```xml
<?xml version="1.0" encoding="utf-8"?>
<Release>
  <Release Version="1.0">
    <Framework Name="dotnetcore1.0" Source="dotnetcore1.0">
      <assemblySearchPath>dependencies/dotnetcore1.0</assemblySearchPath>
    </Framework>
    <Framework Name="dotnetcore2.0" Source="dotnetcore2.0">
      <assemblySearchPath>dependencies/dotnetcore2.0</assemblySearchPath>
    </Framework>
  </Release>
</Release>
```

This would refer to a folder structure as follows:

```
azure-keyvault
|___ dependencies
     |___ dotnetcore1.0
     |___ dotnetcore2.0
|___ 1.0
     |___ dotnetcore1.0
     |___ dotnetcore2.0
```

And the resulting framework index files in the output would be named

- `1.0-dotnetcore1.0`
- `1.0-dotnetcore2.0`

and the corresponding XML would also contain the release version ... so `<Framework Name="dotnetcore1.0" ReleaseVersion="1.0">` and `<Framework Name="dotnetcore2.0" ReleaseVersion="1.0">` for these examples.

If you guys are 👍  on this ... then this change will require

1. a change to the `fx-bootstrap` subcommand, to understand this new structure and write the corresponding configuration file
1. a change to the code that reads the configuration file
1. the code that writes the files in the `FrameworkIndex` folder will be modified to write the corresponding release version.

/cc @conceptdev

**Comment by dend** [comment]
@joelmartinez this looks good to me, I just want to make sure that I understand properly. When we are talking about "releases", I feel like a release has to be associated with a framework, but in the XML example above it looks to be a standalone entry with no declaration of _what_ the release is, just a version. Am I missing something there?

**Comment by joelmartinez** [comment]
@dend good question ... the intent there was for "Release" to be "a release of the librar(y|ies) that we are documenting". This way, we can document that "version _x_ of this set of libraries 'works with': dotnetcore1.0, dotnetcore2.0, .net4.5, etc."

Is there a scenario in which the assemblies contained in a given doc set will have different release cycles and versions?

**Comment by dend** [comment]
@joelmartinez to give a better example, say we have a folder with the following libraries:

* Azure KeyVault
* Azure Storage
* Azure HDInsight
* Azure WebSites
... (etc.)

They all have their separate folders, for example `azurestorage-8.1.1` and `azurestorage-8.1.3` (there can be many versions of a single library that we keep track of) and inside them, we would break down for .NET Framework, .NET Core, etc.

But the idea is that every "framework" (by following the idea of what `mdoc` sees as such) would have several releases within it.

**Comment by joelmartinez** [comment]
heh, ok so I've [mentioned this](https://github.com/mono/api-doc-tools/issues/85#issuecomment-307458336) before, and even your description alludes to the problem ("by following the idea of what mdoc sees as such" referring to "framework") ... the terminology that we're using here is problematic, and does not solve the problem that we're trying to solve.

So we should start by defining all of the handles that we want to be able to adjust in this system:

- Library (such as "**Azure Storage**")
- Library Version (such as "**v3.4** of Azure Storage")
- Framework (such as "**UWP**", or "**Xamarin iOS**")
- Framework Version  (such as ".NET Core **v2.0**")

@dend @Sampy does this represent every bit of data that we need to use to organize these assemblies, and does this nomenclature make sense?

**Comment by dend** [comment]
Here is a rough mock of how I see the general structure: 

![tenative structure](https://user-images.githubusercontent.com/1389609/28546988-a67ce5ee-7081-11e7-88f8-f06f041a8016.jpg)

We can decide on individual terminology based on the diagram. 

@Sampy @joelmartinez

**Comment by joelmartinez** [comment]
Hmm ... so just to be clear, you don't think it's important to configure the "target platform" version systematically? There's already [21 permutations](https://github.com/dotnet/docs/tree/master/xml/FrameworksIndex) of "target platform" and version in what's currently tracked today for the BCL.

**Comment by dend** [comment]
I think I am here with @Sampy - we should keep this simple. Compatible with .NET Core means latest Core - we don't need to break it down per versions of core. Otherwise we create a bunch of unnecessary overhead, it seems.

**Comment by joelmartinez** [comment]
@dend, @Sampy ok ... so what does the frameworksindex.xml file look like in this simpler mode? because right now it uses names like `netcore-1.0`, with the version appended. Do we assume that we can split by `-` and take `[0]` for that name, or does that format need to change? And what would the ideal file structure look like?

**Comment by dend** [comment]
Per my earlier conversation with @joelmartinez, here is a proposal that I have in mind for this, to keep it as simple as possible.

## Configuration

Following the existing configuration convention, we implement something similar to this:

```
<?xml version="1.0" encoding="utf-8"?>
<Frameworks>
    <Framework Name="azurestorage-1.2" Source="azurestorage-1.2">
      <assemblySearchPath>dependencies/azurestorage-1.2</assemblySearchPath>
      <TargetPlatforms>
         <TargetPlatform>netcore</TargetPlatform>
         <TargetPlatform>netfx</TargetPlatform>
         <TargetPlatform>netstandard</TargetPlatform>
      </TargetPlatforms>
    </Framework>
    <Framework Name="azurestorage-1.3" Source="azurestorage-1.3">
      <assemblySearchPath>dependencies/azurestorage-1.3</assemblySearchPath>
    </Framework>
</Frameworks>
```

Specific nuances: 

1. The `azurestorage-1.2` "framework" has versions of .NET Core, .NET Framework and .NET Standard.
2. Following the declaration, dependencies for **each** target platform will be in `assemblySearchPath`+`targetPlatform`, e.g. `dependencies/azurestorage-1.2/netcore`
3. The `azurestorage-1.3` does not have a breakdown per-target, so we just assume that it follows the standard flat structure of binaries in it.

## Output

### azurestorage-1.2

Because there was a number of target platforms provided, we can end up with something similar to:

```
<?xml version="1.0" encoding="utf-8"?>
<Framework Name="azurestorage-1.2">
  <TargetPlatform Name="netcore">
    <Namespace Name="Microsoft.Azure.Batch">
      <Type Name="Microsoft.Azure.Batch.AddTaskCollectionResultHandler" Id="T:Microsoft.Azure.Batch.AddTaskCollectionResultHandler">
        <Member Id="M:Microsoft.Azure.Batch.AddTaskCollectionResultHandler.#ctor(System.Func{Microsoft.Azure.Batch.AddTaskResult,System.Threading.CancellationToken,Microsoft.Azure.Batch.AddTaskResultStatus})" />
        <Member Id="M:Microsoft.Azure.Batch.AddTaskCollectionResultHandler.DefaultAddTaskCollectionResultHandler(Microsoft.Azure.Batch.AddTaskResult,System.Threading.CancellationToken)" />
        <Member Id="P:Microsoft.Azure.Batch.AddTaskCollectionResultHandler.ResultHandler" />
      </Type>
    </Namespace>
  </TargetPlatform>
</Framework>
```
Each platform would get it's own `TargetPlatform` node, with the full breakdown of namespaces/types/members within those.

For cases where no `TargetPlatform` was specified in the configuration, we can wrap all existing namespaces/types/members into a `<TargetPlatform Name="default">`.

**Comment by joelmartinez** [comment]
This is relevant: https://www.hanselman.com/blog/DraftNETGlossaryDiagram.aspx ([official here](https://docs.microsoft.com/en-us/dotnet/standard/glossary) )

I think we should align with the standard glossary ... specifically, the entities we are referencing in these artifacts are (along with what I propose we change them to):

- `Framework` -> `Library` or `Package` ... this one could go either way, because the glossary states that a `package` is specifically a nuget thing, but mdoc doesn't necessarily work directly with nuget packages (I know there's other tooling in your pipeline to extract those), however it seems like your usage would suggest that they're usually collections of libraries, right?
- `TargetPlatform` -> `TargetRuntime` ... the glossary lists runtimes as ".net core, .net framework, or mono"; where platform is OS/hardware. Xamarin.iOS/Android/Mac are ports of Mono to those platforms ... so I think we can consider them as valid "targets".

@Dend, @Sampy ... thoughts? I hate to keep vacillating on this; I think with @Dend's proposal above, we have the "shape" of the data right. I really want to make sure we get the terminology right ... and aligning with the glossary makes sense :)

**Comment by Sampy** [comment]
Going off an official glossary of terms is a good choice and I think that will be very helpful in both making our tool more understandable as well as helping reinforce the terms in the community.

**Comment by dend** [comment]
Just like @Sampy said, I think aligning the terminology here would be great.
