### ISSUE TITLE
Missing namespace in Frameworks Mode

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#88]
If you download [this set of binaries](https://bindrop.blob.core.windows.net/tempdrop/309-bin.zip) (it's already provisioned for FW) and run it through `mdoc`, you will notice that `Microsoft.ServiceFabric.Data.Collections.Preview` has a `ns-*.xml` file, and even a folder, but is not included in `index.xml`.

**Comment by joelmartinez** [comment]
@dend actually, I was mistaken yesterday in thinking I had reproduced the issue (was looking at the wrong NS) ... actually, I don't see `Microsoft.ServiceFabric.Data.Collections.Preview` anywhere. I browsed through a few of the assemblies I thought might have them, including: `servicefabricdata-2.6.204`, and `servicefabricdata-2.7.0-preview5718`.

Do you know what assembly this namespace can be found in?

Could it be that perhaps this namespace (`*.Preview`) was only in the preview release for a short time, and was subsequently removed from the preview?

**Comment by dend** [comment]
@joelmartinez you are right, if I do a fresh pass, the namespace is not there, so it must have been removed. Will have to update the files - let's close this as a non-issue for now.
