### ISSUE TITLE
Support for inheritdoc

### ISSUE THREAD

**Issue by danroth27** [mono/api-doc-tools#91]
The [ASP.NET Core](https://github.com/aspnet/home) doc comments make extensive use of [inheritdoc](http://tunnelvisionlabs.github.io/SHFB/docs-master/SandcastleBuilder/html/79897974-ffc9-4b84-91a5-e50c66a0221d.htm). We would like to see this support in EcmaXML so that we can generate our API refs without having to repeat doc comments everywhere.

**Comment by joelmartinez** [comment]
This feature request is being discussed in another GH issue, #152 ... will close this particular item in lieu of that one.
