### ISSUE TITLE
[mdoc] Preserving remarks created post-factum on import

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#97]
One of the issues that we are running when we are importing documentation from docXML is that any remarks that were created in the post-production ECMAXML are erased in favor of the imported ones. Here is the scenario.

1. We onboard a new set of DLLs and import Roslyn-generated docXMLs, giving us a new batch of ECMAXML files.
2. Writers edit the ECMAXML remarks to add code examples.
3. A new version of a packages comes out, so we re-run the `mdoc` to import the new information.
4. The import will overwrite the remarks already in ECMAXMLs in favor of those that are in the files already.

This issue was brought up by @mmacy with the Azure Storage libraries, that rely heavily on remarks and user-created samples.

**Comment by dend** [comment]
Documenting potential approach outside the issue text. (cc: @joelmartinez @jonpryor)

Something that we can do, potentially, is implement a `--no-rem-overwrite` flag that could potentially help us avoid overwriting just the remarks for files that already exist. Summaries and everything else should be OK to be paved over.

**Comment by joelmartinez** [comment]
@dend A few questions

1. is adding code examples the only use case? or do we want to enable user-submitted/edited remarks text as well?
1. do the use cases in question *have* remarks in the triple slash docs? or do they only have summaries?

The reason I bring it up, is because sure, we can do something like `--no-rem-overwrite`, but that then puts us in a situation where a developer adding `<remarks>` to an existing API's `///` will never see that content published, because the xml stub had already been created. So it's a bit of a leaky abstraction then.

The other potential idea that I mentioned previously, was maybe adding an attribute (`lock="true"`, or `overwrite="false"`, or something) to an element that was edited outside of the triple slash docs. In that case, it can be a bit more selective and ad-hoc ... though admittedly this has the same problem as above.

**Comment by dend** [comment]
@joelmartinez 

1. No, users can add a bunch of other text content to remarks, that way we keep that area as flexible as possible.
2. We don't have one standard case for those - some teams ship some remarks in ///, some don't, so there is no way for us to easily tell.

I like the attribute idea, where we can potentially mark specific remarks as "locked", and in that case, we can communicate to product teams here that they need to be aware of when customers/contributors can set remarks as the source of truth despite potential conflicts with /// items coming from docXMLs.

**Comment by joelmartinez** [comment]
Implementation notes: Changes for this will happen in [`MsxdocDocumentationImporter.ImportDocumentation`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/Updater/MsxdocDocumentationImporter.cs#L47).

Just to choose/propose an implementation based on the discussion above:

1. We'll want to check to see if the existing XML element has an `overwrite="false"` attribute before clearing and replacing it with the element (`remarks`, `summary`, etc) that is being imported.
1. The [`monodoc-ecma.xsd`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Resources/monodoc-ecma.xsd) file will have to be amended to allow for this new attribute. This XSD is used via the `mdoc validate` subcommand.

**Comment by katebialiatka** [comment]
Hello,
I took a look at this issue and have some questions. Could you please comment on them?

1. Is it correct that overwrite="false" attribute will be added manually by the person who alters remarks? If so, do we need to create some kind of instruction to specify rules when and where this attribute can be placed?

2. Is this attribute available only to remarks or for each element that contains text description (like <param> and <summary> ect.)?

3. Is it possible that manually added remarks can contradict with remarks from the code? If so, should we make any notes somewhere that remarks were preserved to let team know? Example which came to my mind is that in newer version parameter was replaced with another one. And remarks contain code sample for older code version and are marked with overwrite="false" attribute.

4. Is it possible that in the newer version element will be removed however overwrite="false" attribute was added in between imports? Should we then preserve such elements or remove action has higher priority and tag needs to be removed?

**Comment by joelmartinez** [comment]
@katebialiatka 

1. Yes, it will be manually added to any element that has been edited by a person (or tool).
1. Yes that is correct.
1. That would be something for the engineering team/author to be responsible for. Essentially, once `overwrite="false"` is added to an element, it becomes the source of truth going forward ... so triple slash content would be ignored.
1. see above point
1. Yes, I will write a simple sample and comment here again shortly

**Comment by joelmartinez** [comment]
@katebialiatka ok, so start with this simple code:

```csharp
using System;
namespace Mdoc.Sample {
  ///<summary>This is the triple slash summary for the class</summary>
  ///<remarks>These are class remarks</remarks>
  public class SampleClass {
    ///<summary>This is a member summary</summary>
    public string name {get;set;}
  }
}
```
Then, you can easily compile this using the command line, making sure to include the [`/doc` option](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/doc-compiler-option), which will put the triple slash docs into an XML file. This file will be _similar_ in content to EcmaXML, but uses different tags, and contains **all types**, which can be unwieldy for maintaining open source docs.
```bash
csc somecode.cs /t:library /doc:somecode.xml
```
With that XML file in hand, then you can use _mdoc_ to import that content into a set of EcmaXML docs:
```bash
./bin/Release/mdoc.exe update somecode.dll -out somecode-docs -import somecode.xml
```
This will create a `somecode-docs` folder that contains EcmaXML, and includes the text from the triple slash docs ... for example, in `somecode-docs/Mdoc.Sample/SampleClass.xml`, we find:
```xml
  <Docs>
    <summary>This is the triple slash summary for the class</summary>
    <remarks>These are class remarks</remarks>
  </Docs>
```
Subsequent runs of the `mdoc update` statement above will update the XML if the text in the `somecode.cs` file changes

**Comment by katebialiatka** [comment]
@joelmartinez Thanks for all your comments - it helped a lot.
Just one more clarification is needed in regards to the second question.

`Is this attribute available only to remarks or for each element that contains text description (like <param> and <summary> ect.)?`
Does it means from your answer that this attribute will be applied only to remarks?

As we can see from the flow, other tags can be rewritten too (like summary and params). Probably it make sense to prevent rewriting for any other tag marked with overwrite attribute?

**Comment by joelmartinez** [comment]
@katebialiatka look at it this way, in the importer code, although there are specific references to nodes: summary, remarks, value, returns, param, typeparam, altmember, exception, permission, and seealso ... the [`default:`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/Updater/MsxdocDocumentationImporter.cs#L113) case for the switch statement that iterates through all of the children of the member node will import any other tag that happens to be in there. 

So firstly, all of those cases in that method need to have the logic to **not** copy/import if the attribute is present on the target node. 

And _then_ any element that would potentially be affected (ie. anything under `Type`, `Member`, or `Docs` elements ... I think, please verify my assumption that these are the only applicable parents), would have to have the attribute added as an optional attribute in [the xsd](https://github.com/mono/api-doc-tools/blob/master/mdoc/Resources/monodoc-ecma.xsd) :)

**Comment by asokolovskiy15** [comment]
Hi Joel
I have some questions about the ticket.

1.For this ticket, I applied changes in code and xsd file. But I still have one question: what should be the behavior when a user mistypes boolean value. For example, “faKse” instead of "false"? Should we throw an exception or apply some default behavior (please, specify the default action for this case)?
This case is possible because Validate is not applied during the update command. However, operation validate works correctly when it is called separately.


2. When we import the following documentation from docXML   

<returns>NewReturns</returns>
<value>NewValue</value>

We get the following elements

<value>NewReturns</value>
<value>NewValue</value>

Is this correct behavior? It happens because the property ReturnIsReturn is always equal to “false” and only after writing a file the property becomes true.

**Comment by joelmartinez** [comment]
@asokolovskiy15 

1. I tend to prefer more flexible approaches ... so during an update command, if a value has `faKse`, we can just keep on going in the `update` subcommand (perhaps writing a warning to the output stream). As long as it notes the error during `validate`.
2. Interesting ... it should definitively be translating that to `returns`, as that is the expected value. You should fix this behavior :)

**Comment by joelmartinez** [comment]
it would seem that this created a regression:

```
2017-10-28T05:11:15.6822016Z Updating: Microsoft.Azure.Documents.SystemFunctions.TypeCheckFunctionsExtensions
2017-10-28T05:11:19.3056944Z ##[error]mdoc: System.Xml.XPath.XPathException: Expression must evaluate to a node-set.
   at MS.Internal.Xml.XPath.XPathParser.ParseNodeTest(AstNode qyInput, AxisType axisType, XPathNodeType nodeType)
   at MS.Internal.Xml.XPath.XPathParser.ParseStep(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseRelativeLocationPath(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseLocationPath(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParsePathExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseUnionExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseUnaryExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseMultiplicativeExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseAdditiveExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseRelationalExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseEqualityExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseAndExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseOrExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseExpresion(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseXPathExpresion(String xpathExpresion)
   at System.Xml.XPath.XPathExpression.Compile(String xpath, IXmlNamespaceResolver nsResolver)
   at System.Xml.XPath.XPathNavigator.Select(String xpath)
   at System.Xml.XmlNode.SelectNodes(String xpath)
   at Mono.Documentation.Updater.MsxdocDocumentationImporter.ImportDocumentation(DocsNodeInfo info)
   at Mono.Documentation.MDocUpdater.MakeDocNode(DocsNodeInfo info, IEnumerable`1 setimporters)
   at Mono.Documentation.MDocUpdater.UpdateMember(DocsNodeInfo info, FrameworkTypeEntry typeEntry)
   at Mono.Documentation.MDocUpdater.DoUpdateType2(String message, XmlDocument basefile, TypeDefinition type, FrameworkTypeEntry typeEntry, String output, Boolean insertSince)
   at Mono.Documentation.MDocUpdater.DoUpdateType(TypeDefinition type, FrameworkTypeEntry typeEntry, String basepath, String dest)
   at Mono.Documentation.MDocUpdater.DoUpdateAssembly(AssemblySet assemblySet, AssemblyDefinition assembly, XmlElement index_types, String source, String dest, HashSet`1 goodfiles)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

@asokolovskiy15 ... see if you can try to recreate the issue in an integration test. Look at calls in `MsxdocDocumentationImporter.ImportDocumentation` that would result in an xpath exception if they don't result in a node set.

**Comment by asokolovskiy15** [comment]
@joelmartinez  
As I can see from the trace, you use `Microsoft.Azure.Documents.Client.dll`.
I have found `Microsoft.Azure.Documents.Client.xml` in a nuget package. In this file we can see:

`<seealso cref="P:Microsoft.Azure.Documents.Client.DocumentClient.ConnectionPolicy"/>`
`<seealso cref="P:Microsoft.Azure.Documents.Client.DocumentClient.ConsistencyLevel"/>///`

Our parser recognizes `///` as a separate element with `Name="#text"`. So, `SelectSingleNode("#text")` throws an exception. How should we deal with such an XML?
Some information about nodeName: https://www.w3schools.com/jsref/prop_node_nodename.asp

Also, I have some concern about this xml. This file have following elements `value`, `a`, `threadSafety` etc. In this regard, the command `validate` outputs an error according to the xsd scheme.

**Comment by dend** [comment]
@twitchax do you know who manages the source for `Microsoft.Azure.Documents.Client` and where can we find it? There is an issue with a /// comment introduced in the package, and that breaks the CI.

cc: @asokolovskiy15 @joelmartinez

**Comment by kirankumarkolli** [comment]
I manage documents SDK. 
@dend what's the ask here?

**Comment by dend** [comment]
Followed up with @kirankumarkolli over email - this is being addressed.

**Comment by dend** [comment]
@asokolovskiy15 do you recall what version of the NuGet package that comment was present in? I've scanned the latest 4 and see that the XML is in good shape.

cc: @joelmartinez
